import { buildCapabilityDiscoveryRunId, createCapabilityCandidate, sha256Utf8, stableJsonStringify, type CapabilityCandidate, type CapabilityCandidateInput, type CapabilityDiscoveryRun, type CapabilityKernelOutput } from "../../../../lib/career/capability-core";

const discoveryIdentity = { sourceBundleHash: "SOURCE_HASH", kernelVersion: "discovery-v1", promptChecksum: "DISCOVERY_PROMPT", provider: "gemini", model: "discovery-model", schemaVersion: "discovery-schema-v1" };
export const DISCOVERY_RUN_ID = buildCapabilityDiscoveryRunId(discoveryIdentity);
const audit = (capabilities: CapabilityCandidateInput[]) => ({ source_documents_examined: 1, capability_count: capabilities.length, atomic_capability_count: capabilities.filter((candidate) => candidate.capability_scope === "ATOMIC").length, composite_capability_count: capabilities.filter((candidate) => candidate.capability_scope === "COMPOSITE").length, attribution_pass_completed: true, target_state_ownership_pass_completed: true, atomic_extraction_pass_completed: true, method_capability_pass_completed: true, composite_reconstruction_pass_completed: true, global_convergence_pass_completed: true, inventory_reconciliation_pass_completed: true, final_reconciliation_produced_new_capabilities: false, unresolved_target_operations: 0, segments_classified_as_external_source_content: 0, segments_classified_as_target_subject_operation: 0, segments_classified_as_target_subject_designed_target_state: 0, segments_classified_as_target_organization_capability: 0, segments_excluded_due_to_attribution_ambiguity: 0 });
const inputFor = (label: string): CapabilityCandidateInput => ({ canonical_name: `Name ${label}`, capability_scope: "ATOMIC", structural_definition: `Definition ${label}`, primary_domain: null, demonstrated_capability_level: null, model_confidence: 0.9, evidence_mode: "EXPLICIT", evidence: [{ source_document: "DOC_A", location: "p1", exact_quote: "Proof" }] });
export const kernelInputFor = (candidate: CapabilityCandidate): CapabilityCandidateInput => ({ canonical_name: candidate.proposedCanonicalName, capability_scope: candidate.proposedScope, structural_definition: candidate.structuralDefinition, primary_domain: candidate.proposedPrimaryDomain, demonstrated_capability_level: candidate.proposedDemonstratedLevel, model_confidence: candidate.modelConfidence, evidence_mode: candidate.evidenceMode, evidence: candidate.evidenceClaims.map((claim) => ({ source_document: claim.sourceDocumentRef, location: claim.declaredLocation, exact_quote: claim.exactQuote })) });
export const verifiedCandidate = (label: string, overrides: Partial<CapabilityCandidate> = {}): CapabilityCandidate => { const candidate = createCapabilityCandidate(DISCOVERY_RUN_ID, inputFor(label)); return { ...candidate, status: "EVIDENCE_PASSED", evidenceClaims: candidate.evidenceClaims.map((claim) => ({ ...claim, verification: { status: "VERIFIED", matchedDocId: "DOC_A" } })), ...overrides }; };
export const rejectedCandidate = (label: string): CapabilityCandidate => { const candidate = verifiedCandidate(label); return { ...candidate, status: "EVIDENCE_REJECTED", evidenceClaims: candidate.evidenceClaims.map((claim) => ({ ...claim, verification: { status: "REJECTED_QUOTE_NOT_FOUND" } })) }; };
export const discoveryRun = (candidates: CapabilityCandidate[], kernelOutput?: CapabilityKernelOutput): CapabilityDiscoveryRun => { const output = kernelOutput ?? { kernel_version: "discovery-v1", capabilities: candidates.map(kernelInputFor), coverage_audit: audit(candidates.map(kernelInputFor)) }; return { runId: DISCOVERY_RUN_ID, sourceBundleHash: discoveryIdentity.sourceBundleHash, kernelVersion: discoveryIdentity.kernelVersion, prompt: { checksum: discoveryIdentity.promptChecksum }, inference: { provider: discoveryIdentity.provider, model: discoveryIdentity.model }, schemaVersion: discoveryIdentity.schemaVersion, status: "COMPLETED", rawOutputHash: sha256Utf8(stableJsonStringify(output)), payload: { kernelOutput: output, candidates, coverageValidation: { status: "PASSED" } }, createdAt: "2026-01-01T00:00:00.000Z", completedAt: "2026-01-01T00:00:00.000Z" }; };
export const convergenceOutput = (candidateIds: string[]) => ({ convergence_version: "convergence-v1", groups: candidateIds.length ? [{ group_key: "group-a", member_candidate_ids: candidateIds, canonical_name: "Canonical capability", capability_scope: "ATOMIC" as const, structural_definition: "Canonical definition", primary_domain: null }] : [], relations: [], reconciliation_audit: { input_candidate_count: candidateIds.length, grouped_candidate_count: candidateIds.length, group_count: candidateIds.length ? 1 : 0, same_capability_merge_count: Math.max(0, candidateIds.length - 1), unresolved_relation_count: 0, reconciliation_pass_completed: true } });
