import { describe, expect, it } from "vitest";
import { InMemoryCapabilityCoreRepository, PostgresCapabilityCoreRepository, type CapabilityConvergenceRun } from "../../../../lib/career/capability-core";

const run: CapabilityConvergenceRun = { runKind: "CAPABILITY_CONVERGENCE", convergenceRunId: "CONV_TEST", discoveryRunId: "RUN_DISCOVERY", discoveryRawOutputHash: "discovery-raw", sourceBundleHash: "SOURCE", kernelVersion: "v", prompt: { checksum: "checksum" }, inference: { provider: "gemini", model: "m" }, schemaVersion: "schema", algorithmVersion: "algorithm", status: "COMPLETED", rawOutputHash: "raw", payload: { convergenceOutput: { convergence_version: "v", groups: [], relations: [], reconciliation_audit: { input_candidate_count: 0, grouped_candidate_count: 0, group_count: 0, same_capability_merge_count: 0, unresolved_relation_count: 0, reconciliation_pass_completed: true } }, canonicalDrafts: [], proposedRelations: [], eligibleCandidateIds: [], excludedCandidateIds: [], reconciliation: { status: "PASSED" } }, createdAt: "now", completedAt: "now" };
function fakeDatabase(racePayload?: unknown) { let stored: unknown; return { insert: () => ({ values: (value: { payload: unknown }) => ({ onConflictDoNothing: () => ({ returning: async () => { if (racePayload) { stored = racePayload; return []; } if (stored) return []; stored = value.payload; return [{ runId: "CONV_TEST" }]; } }) }) }), select: () => ({ from: () => ({ where: () => ({ limit: async () => stored ? [{ payload: stored }] : [] }) }) }) }; }
describe("Capability Convergence repository", () => {
  it("deep-clones in-memory runs and rejects divergent immutable saves", async () => { const repository = new InMemoryCapabilityCoreRepository(); await repository.saveConvergenceRun(run); const returned = await repository.getConvergenceRunById(run.convergenceRunId); returned!.payload.eligibleCandidateIds.push("mutated"); expect((await repository.getConvergenceRunById(run.convergenceRunId))!.payload.eligibleCandidateIds).toEqual([]); await expect(repository.saveConvergenceRun({ ...run, status: "COMPLETED", rawOutputHash: "other" })).rejects.toThrow("IMMUTABLE_CONVERGENCE_RUN_CONFLICT"); });
  it.each([[undefined, false], [run, false], [{ ...run, rawOutputHash: "other" }, true]])("round-trips and resolves insert races", async (racePayload, rejects) => { const repository = new PostgresCapabilityCoreRepository(fakeDatabase(racePayload) as never); if (rejects) await expect(repository.saveConvergenceRun(run)).rejects.toThrow("IMMUTABLE_CONVERGENCE_RUN_CONFLICT"); else { await repository.saveConvergenceRun(run); await expect(repository.getConvergenceRunById(run.convergenceRunId)).resolves.toEqual(run); await expect(repository.saveConvergenceRun(run)).resolves.toBeUndefined(); } });
});
