import { eq } from "drizzle-orm";
import type { PostgresJsDatabase } from "drizzle-orm/postgres-js";
import { assertTargetRequirementEntityAdmission } from "../../target/role/requirement/contract";
import { assertTargetRequirementRawProviderOutputArtifact, assertTargetRequirementReconstructionBatchRun, assertTargetRequirementReconstructionResult, sameTargetRequirementArtifact, type TargetRequirementRawProviderOutputArtifact, type TargetRequirementReconstructionBatchRun, type TargetRequirementReconstructionResult } from "../../target/role/requirement/artifact";
import type { TargetRequirementArtifactRepository } from "../../target/role/requirement/artifact-persistence";
import type { TargetRequirementEntityAdmission } from "../../target/role/requirement/types";
import { targetRequirementEntityAdmissions, targetRequirementRawProviderOutputs, targetRequirementReconstructionBatchRuns, targetRequirementReconstructionResults } from "./postgres-schema";
const fail = (code: string): never => { throw new Error(code); };
async function write<T>(insert: Promise<unknown[]>, read: () => Promise<T | null>, value: T): Promise<T> { const inserted = await insert; const winner = await read(); if (winner === null) fail("ERR_TARGET_REQUIREMENT_ARTIFACT_PERSISTENCE_INVALID"); if (!sameTargetRequirementArtifact(winner, value)) fail(inserted.length ? "ERR_TARGET_REQUIREMENT_ARTIFACT_PERSISTENCE_INVALID" : "ERR_TARGET_REQUIREMENT_ARTIFACT_IMMUTABLE_CONFLICT"); return structuredClone(winner) as T; }
export class PostgresTargetRequirementArtifactRepository implements TargetRequirementArtifactRepository {
  constructor(private readonly database: PostgresJsDatabase) {}
  async getRawProviderOutputByRef(id: string): Promise<TargetRequirementRawProviderOutputArtifact | null> { const rows = await this.database.select().from(targetRequirementRawProviderOutputs).where(eq(targetRequirementRawProviderOutputs.rawProviderOutputRef, id)).limit(1); if (!rows.length) return null; const row = rows[0]; try { assertTargetRequirementRawProviderOutputArtifact(row.payload); if (row.rawProviderOutputRef !== row.payload.rawProviderOutputRef || row.rawProviderOutputHash !== row.payload.rawProviderOutputHash) fail("ERR_TARGET_REQUIREMENT_ARTIFACT_PERSISTENCE_INVALID"); return structuredClone(row.payload); } catch { return fail("ERR_TARGET_REQUIREMENT_ARTIFACT_PERSISTENCE_INVALID"); } }
  async getBatchRunById(id: string): Promise<TargetRequirementReconstructionBatchRun | null> { const rows = await this.database.select().from(targetRequirementReconstructionBatchRuns).where(eq(targetRequirementReconstructionBatchRuns.targetRequirementReconstructionBatchRunId, id)).limit(1); if (!rows.length) return null; const row = rows[0]; try { assertTargetRequirementReconstructionBatchRun(row.payload); if (row.targetRequirementReconstructionBatchRunId !== row.payload.targetRequirementReconstructionBatchRunId || row.rawProviderOutputRef !== row.payload.rawProviderOutputRef) fail("ERR_TARGET_REQUIREMENT_ARTIFACT_PERSISTENCE_INVALID"); return structuredClone(row.payload); } catch { return fail("ERR_TARGET_REQUIREMENT_ARTIFACT_PERSISTENCE_INVALID"); } }
  async getResultById(id: string): Promise<TargetRequirementReconstructionResult | null> { const rows = await this.database.select().from(targetRequirementReconstructionResults).where(eq(targetRequirementReconstructionResults.targetRequirementReconstructionResultId, id)).limit(1); if (!rows.length) return null; const row = rows[0]; try { assertTargetRequirementReconstructionResult(row.payload); if (row.targetRequirementReconstructionResultId !== row.payload.targetRequirementReconstructionResultId || row.targetRequirementReconstructionBatchRunId !== row.payload.targetRequirementReconstructionBatchRunId || row.targetRoleProfileRevisionId !== row.payload.targetRoleProfileRevisionId) fail("ERR_TARGET_REQUIREMENT_ARTIFACT_PERSISTENCE_INVALID"); return structuredClone(row.payload); } catch { return fail("ERR_TARGET_REQUIREMENT_ARTIFACT_PERSISTENCE_INVALID"); } }
  async getAdmissionById(id: string): Promise<TargetRequirementEntityAdmission | null> { const rows = await this.database.select().from(targetRequirementEntityAdmissions).where(eq(targetRequirementEntityAdmissions.targetRequirementEntityAdmissionId, id)).limit(1); if (!rows.length) return null; const row = rows[0]; try { assertTargetRequirementEntityAdmission(row.payload); if (row.targetRequirementEntityAdmissionId !== row.payload.targetRequirementEntityAdmissionId || row.targetRequirementReconstructionResultId !== row.payload.targetRequirementReconstructionResultId) fail("ERR_TARGET_REQUIREMENT_ARTIFACT_PERSISTENCE_INVALID"); return structuredClone(row.payload); } catch { return fail("ERR_TARGET_REQUIREMENT_ARTIFACT_PERSISTENCE_INVALID"); } }
  async persistRawProviderOutput(value: TargetRequirementRawProviderOutputArtifact) { assertTargetRequirementRawProviderOutputArtifact(value); return write(this.database.insert(targetRequirementRawProviderOutputs).values({ rawProviderOutputRef: value.rawProviderOutputRef, rawProviderOutputHash: value.rawProviderOutputHash, payload: structuredClone(value) }).onConflictDoNothing().returning(), () => this.getRawProviderOutputByRef(value.rawProviderOutputRef), value); }
  async persistBatchRun(value: TargetRequirementReconstructionBatchRun) { assertTargetRequirementReconstructionBatchRun(value); return write(this.database.insert(targetRequirementReconstructionBatchRuns).values({ targetRequirementReconstructionBatchRunId: value.targetRequirementReconstructionBatchRunId, rawProviderOutputRef: value.rawProviderOutputRef, payload: structuredClone(value) }).onConflictDoNothing().returning(), () => this.getBatchRunById(value.targetRequirementReconstructionBatchRunId), value); }
  async persistResult(value: TargetRequirementReconstructionResult) { assertTargetRequirementReconstructionResult(value); return write(this.database.insert(targetRequirementReconstructionResults).values({ targetRequirementReconstructionResultId: value.targetRequirementReconstructionResultId, targetRequirementReconstructionBatchRunId: value.targetRequirementReconstructionBatchRunId, targetRoleProfileRevisionId: value.targetRoleProfileRevisionId, payload: structuredClone(value) }).onConflictDoNothing().returning(), () => this.getResultById(value.targetRequirementReconstructionResultId), value); }
  async persistAdmission(value: TargetRequirementEntityAdmission) { assertTargetRequirementEntityAdmission(value); return write(this.database.insert(targetRequirementEntityAdmissions).values({ targetRequirementEntityAdmissionId: value.targetRequirementEntityAdmissionId, targetRequirementReconstructionResultId: value.targetRequirementReconstructionResultId, payload: structuredClone(value) }).onConflictDoNothing().returning(), () => this.getAdmissionById(value.targetRequirementEntityAdmissionId), value); }
}
