import { eq } from "drizzle-orm";
import type { PostgresJsDatabase } from "drizzle-orm/postgres-js";
import { assertTargetRoleOrganizationBindingRevision, createBoundTargetRoleOrganizationBindingRevisionPersister, sameTargetRoleOrganizationBindingRevisionData, type BoundTargetRoleOrganizationBindingRevisionPersister, type TargetRoleOrganizationBindingOperandLookup, type TargetRoleOrganizationBindingRevision, type TargetRoleOrganizationBindingRevisionRepository } from "../../target/role";
import { targetRoleOrganizationBindingRevisions } from "./postgres-schema";
const invalid = (): never => { throw new Error("ERR_TARGET_ROLE_ORGANIZATION_BINDING_REVISION_POSTGRES_RECORD_INVALID"); };
const nonEmpty = (value: unknown): value is string => typeof value === "string" && value.length > 0;
function row(value: { targetRoleOrganizationBindingRevisionId: unknown; targetRoleEntityId: unknown; targetRoleSourceBindingRevisionId: unknown; targetOrganizationRevisionId: unknown; previousRevisionId: unknown; payload: unknown }, requested?: string): TargetRoleOrganizationBindingRevision {
  try { if (!nonEmpty(value.targetRoleOrganizationBindingRevisionId) || !nonEmpty(value.targetRoleEntityId) || !nonEmpty(value.targetRoleSourceBindingRevisionId) || !nonEmpty(value.targetOrganizationRevisionId) || (value.previousRevisionId !== null && !nonEmpty(value.previousRevisionId)) || (requested !== undefined && value.targetRoleOrganizationBindingRevisionId !== requested)) return invalid(); const revision = structuredClone(value.payload) as TargetRoleOrganizationBindingRevision; assertTargetRoleOrganizationBindingRevision(revision); if (revision.targetRoleOrganizationBindingRevisionId !== value.targetRoleOrganizationBindingRevisionId || revision.targetRoleEntityId !== value.targetRoleEntityId || revision.targetRoleSourceBindingRevisionId !== value.targetRoleSourceBindingRevisionId || revision.targetOrganizationRevisionId !== value.targetOrganizationRevisionId || revision.previousRevisionId !== value.previousRevisionId) return invalid(); return structuredClone(revision); } catch { return invalid(); }
}
/** PK conflict rereads a durable immutable winner; it never authorizes update or replacement semantics. */
export class PostgresTargetRoleOrganizationBindingRevisionRepository implements TargetRoleOrganizationBindingRevisionRepository {
  constructor(private readonly database: PostgresJsDatabase, private readonly operands: TargetRoleOrganizationBindingOperandLookup) {}
  async getRevisionById(id: string): Promise<TargetRoleOrganizationBindingRevision | null> { const values = await this.database.select().from(targetRoleOrganizationBindingRevisions).where(eq(targetRoleOrganizationBindingRevisions.targetRoleOrganizationBindingRevisionId, id)).limit(1); return values.length === 0 ? null : row(values[0], id); }
  createTargetRoleOrganizationBindingRevisionPersister(): BoundTargetRoleOrganizationBindingRevisionPersister { return createBoundTargetRoleOrganizationBindingRevisionPersister({ getRevisionById: this.getRevisionById.bind(this), getTargetRoleSourceBindingRevisionById: this.operands.getTargetRoleSourceBindingRevisionById.bind(this.operands), getTargetOrganizationRevisionById: this.operands.getTargetOrganizationRevisionById.bind(this.operands), writeRevision: this.#write.bind(this) }); }
  async #write(revision: TargetRoleOrganizationBindingRevision): Promise<void> { const inserted = await this.database.insert(targetRoleOrganizationBindingRevisions).values({ targetRoleOrganizationBindingRevisionId: revision.targetRoleOrganizationBindingRevisionId, targetRoleEntityId: revision.targetRoleEntityId, targetRoleSourceBindingRevisionId: revision.targetRoleSourceBindingRevisionId, targetOrganizationRevisionId: revision.targetOrganizationRevisionId, previousRevisionId: revision.previousRevisionId, payload: structuredClone(revision) }).onConflictDoNothing().returning({ id: targetRoleOrganizationBindingRevisions.targetRoleOrganizationBindingRevisionId }); if (inserted.length === 1) return; let winner: TargetRoleOrganizationBindingRevision | null; try { winner = await this.getRevisionById(revision.targetRoleOrganizationBindingRevisionId); } catch (error) { if (error instanceof Error && error.message === "ERR_TARGET_ROLE_ORGANIZATION_BINDING_REVISION_POSTGRES_RECORD_INVALID") throw new Error("ERR_TARGET_ROLE_ORGANIZATION_BINDING_REVISION_PERSISTENCE_INVALID"); throw error; } if (winner === null) throw new Error("ERR_TARGET_ROLE_ORGANIZATION_BINDING_REVISION_PERSISTENCE_INVALID"); if (!sameTargetRoleOrganizationBindingRevisionData(winner, revision)) throw new Error("ERR_TARGET_ROLE_ORGANIZATION_BINDING_REVISION_IMMUTABLE_CONFLICT"); }
}
