import { describe, expect, it } from "vitest";
import { createDecisionAuthorityGrantRevision, InMemoryDecisionAuthorityGrantRevisionRepository } from "../../../../lib/career/relation/decision-authority";
import { createCareerDecisionContextRevision, InMemoryCareerDecisionContextRevisionRepository } from "../../../../lib/career/relation/decision-context";
import { deriveEvolutionInputStateId } from "../../../../lib/career/relation/evolution-input";
import { deriveRecommendationPolicyRevisionId, deriveRecommendationProposal, InMemoryRecommendationProposalRepository } from "../../../../lib/career/relation/recommendation-proposal";
import { createHumanDecisionRecord, derivationReplayHumanDecisionRecord, InMemoryHumanDecisionRecordRepository, produceAndPersistHumanDecisionRecord, semanticReplayHumanDecisionRecord } from "../../../../lib/career/relation/decision-record";
const stamp="2027-02-01T00:00:00.000Z";
const policySemantic={provenance:{origin:"EXPLICIT_POLICY_DECLARATION" as const,actorId:"POLICY",authorityEvidenceRef:"evidence://policy"},rules:[{evolutionInputClass:"INCREASE_DEMONSTRATED_LEVEL_INPUT" as const,action:"PROPOSE" as const,recommendationKind:"DEMONSTRATED_LEVEL_RECOMMENDATION" as const},{evolutionInputClass:"RESOLVE_SEMANTIC_UNCERTAINTY_INPUT" as const,action:"PROPOSE" as const,recommendationKind:"SEMANTIC_UNCERTAINTY_RESOLUTION_RECOMMENDATION" as const},{evolutionInputClass:"RESOLVE_TARGET_UNCERTAINTY_INPUT" as const,action:"PROPOSE" as const,recommendationKind:"TARGET_UNCERTAINTY_RESOLUTION_RECOMMENDATION" as const},{evolutionInputClass:"STRENGTHEN_EVIDENCE_INPUT" as const,action:"PROPOSE" as const,recommendationKind:"EVIDENCE_STRENGTHENING_RECOMMENDATION" as const}],recommendationPolicyImplementationVersion:"recommendation-v1",schemaVersion:"RECOMMENDATION_POLICY_REVISION_V1" as const};
const policy={recommendationPolicyRevisionId:deriveRecommendationPolicyRevisionId(policySemantic),...policySemantic,createdAt:stamp};
function proposal(code="LEVEL_BELOW_RELATION",inputClass:any="INCREASE_DEMONSTRATED_LEVEL_INPUT",disposition:any="DERIVABLE"){const family=code==="LEVEL_BELOW_RELATION"||code==="SEMANTIC_PARTIAL_RELATION"?"STRUCTURAL_DIFFERENCE":"EPISTEMIC_UNCERTAINTY";const dimension=code==="LEVEL_BELOW_RELATION"?"LEVEL":code==="SEMANTIC_PARTIAL_RELATION"?"SEMANTIC":"EVIDENCE";const semantic={tensionStateId:"TSN_T11C",roleRelationId:"RRL_T11C",verifiedCapabilitySnapshotId:"SNAP_T11C",targetRoleProfileRevisionId:"TRP_T11C",targetRoleRequirementInventoryId:"INV_T11C",items:[{evolutionInputClass:inputClass,derivationDisposition:disposition,tensionClassificationFamily:family as any,tensionClassificationCode:code,subjectKind:"REQUIREMENT" as const,dimension:dimension as any,targetRequirementEntityId:null,targetRequirementRevisionIds:[],requirementRelationAggregateId:null,candidateCapabilityOperandId:null,capabilityRequirementRelationId:null,capabilityRequirementRelationEvaluationResultId:null,necessityStates:[]}],derivationPolicyLineage:{evolutionInputDerivationPolicyVersion:"evolution-v1"},proposalState:"PROPOSAL_ONLY" as const,authorityState:"NONE" as const,schemaVersion:"EVOLUTION_INPUT_STATE_V1" as const};const eis={evolutionInputStateId:deriveEvolutionInputStateId(semantic),...semantic,createdAt:stamp};return deriveRecommendationProposal(eis,policy,{version:"recommendation-v1"},stamp)}
const authority=createDecisionAuthorityGrantRevision({grantorActorId:"GRANTOR",authorizedActorId:"DECIDER",authorityScope:"CAREER_RECOMMENDATION_DECISION",permittedDecisionClasses:["ACCEPT_RECOMMENDATION","DEFER_DECISION","REJECT_RECOMMENDATION","REQUEST_FURTHER_EVIDENCE","REQUEST_TARGET_CLARIFICATION"],permittedSubjectKinds:["RCP_ITEM"],authorityEvidenceRefs:["evidence://grant"],declaredAt:stamp,effectiveFrom:stamp,effectiveUntil:null,createdAt:stamp});
function context(p=proposal()){return createCareerDecisionContextRevision(authority,p,{decisionAuthorityGrantRevisionId:authority.decisionAuthorityGrantRevisionId,recommendationProposalId:p.recommendationProposalId,decisionSubjects:[{recommendationProposalId:p.recommendationProposalId,sourceEvolutionInputItemOrdinal:0}],contextEvidenceRefs:[],createdAt:stamp})}
function input(c:any="ACCEPT_RECOMMENDATION",more:any={}){return {careerDecisionContextRevisionId:"",declarantActorId:"DECIDER",declarationClass:c,declaredAt:stamp,declarationEvidenceRefs:["evidence://declaration"],createdAt:stamp,...more}}
describe("T11C HumanDecisionRecord",()=>{
  it("creates a non-regenerable human declaration from exact context lineage",async()=>{const p=proposal(),c=context(p),authorities=new InMemoryDecisionAuthorityGrantRevisionRepository(),proposals=new InMemoryRecommendationProposalRepository(),contexts=new InMemoryCareerDecisionContextRevisionRepository(),records=new InMemoryHumanDecisionRecordRepository();await authorities.persistDecisionAuthorityGrantRevision(authority);await proposals.persistRecommendationProposal(p);await contexts.persistCareerDecisionContextRevision(c);const value=await produceAndPersistHumanDecisionRecord(input("ACCEPT_RECOMMENDATION",{careerDecisionContextRevisionId:c.careerDecisionContextRevisionId}),{authorities,proposals,contexts,records});expect(value.humanDecisionRecordId).toMatch(/^DCR_[0-9A-F]{32}$/);expect(value.decisionSubjects).toEqual(c.decisionSubjects);expect(value).not.toHaveProperty("commitment");expect(value).not.toHaveProperty("execution");await expect(semanticReplayHumanDecisionRecord(value.humanDecisionRecordId,{authorities,proposals,contexts,records})).resolves.toEqual(value);await expect(derivationReplayHumanDecisionRecord(value.humanDecisionRecordId,{authorities,proposals,contexts,records})).resolves.toEqual(value)});
  it("accepts and rejects only proposed subjects; defer preserves any exact context subject",()=>{const p=proposal(),c=context(p);expect(createHumanDecisionRecord(c,authority,p,input("ACCEPT_RECOMMENDATION",{careerDecisionContextRevisionId:c.careerDecisionContextRevisionId})).declarationClass).toBe("ACCEPT_RECOMMENDATION");expect(createHumanDecisionRecord(c,authority,p,input("REJECT_RECOMMENDATION",{careerDecisionContextRevisionId:c.careerDecisionContextRevisionId})).declarationClass).toBe("REJECT_RECOMMENDATION");const blocked=proposal("SEMANTIC_PARTIAL_RELATION",null,"NOT_DERIVABLE"),blockedContext=context(blocked);expect(()=>createHumanDecisionRecord(blockedContext,authority,blocked,input("ACCEPT_RECOMMENDATION",{careerDecisionContextRevisionId:blockedContext.careerDecisionContextRevisionId}))).toThrow("ERR_HUMAN_DECISION_SUBJECT_NOT_ADMISSIBLE");expect(createHumanDecisionRecord(blockedContext,authority,blocked,input("DEFER_DECISION",{careerDecisionContextRevisionId:blockedContext.careerDecisionContextRevisionId})).declarationClass).toBe("DEFER_DECISION")});
  it("uses exact source codes for evidence and target clarification, never generic blocking",()=>{const evidenceProposal=proposal("EVIDENCE_INSUFFICIENT","STRENGTHEN_EVIDENCE_INPUT"),evidenceContext=context(evidenceProposal);expect(createHumanDecisionRecord(evidenceContext,authority,evidenceProposal,input("REQUEST_FURTHER_EVIDENCE",{careerDecisionContextRevisionId:evidenceContext.careerDecisionContextRevisionId})).declarationClass).toBe("REQUEST_FURTHER_EVIDENCE");const targetProposal=proposal("REQUIREMENT_RELATION_AGGREGATE_SET_UNRESOLVED","RESOLVE_TARGET_UNCERTAINTY_INPUT"),targetContext=context(targetProposal);expect(createHumanDecisionRecord(targetContext,authority,targetProposal,input("REQUEST_TARGET_CLARIFICATION",{careerDecisionContextRevisionId:targetContext.careerDecisionContextRevisionId})).declarationClass).toBe("REQUEST_TARGET_CLARIFICATION");expect(()=>createHumanDecisionRecord(targetContext,authority,targetProposal,input("REQUEST_FURTHER_EVIDENCE",{careerDecisionContextRevisionId:targetContext.careerDecisionContextRevisionId}))).toThrow("ERR_HUMAN_DECISION_SUBJECT_NOT_ADMISSIBLE")});
  it("fails closed for actor, class, interval, evidence, and identity divergence",()=>{const p=proposal(),c=context(p),valid=input("ACCEPT_RECOMMENDATION",{careerDecisionContextRevisionId:c.careerDecisionContextRevisionId});expect(()=>createHumanDecisionRecord(c,authority,p,{...valid,declarantActorId:"OTHER"})).toThrow("ERR_HUMAN_DECISION_DECLARANT_MISMATCH");expect(()=>createHumanDecisionRecord(c,authority,p,{...valid,declaredAt:"2026-01-01T00:00:00.000Z"})).toThrow("ERR_HUMAN_DECISION_AUTHORITY_NOT_APPLICABLE");expect(()=>createHumanDecisionRecord(c,authority,p,{...valid,declarationEvidenceRefs:[]})).toThrow("ERR_HUMAN_DECISION_INVALID");const one=createHumanDecisionRecord(c,authority,p,valid),two=createHumanDecisionRecord(c,authority,p,{...valid,createdAt:"2028-01-01T00:00:00.000Z"});expect(one.humanDecisionRecordId).toBe(two.humanDecisionRecordId);expect(()=>createHumanDecisionRecord(c,authority,p,{...valid,declarationClass:"AUTHORIZED_ACTION"})).toThrow("ERR_HUMAN_DECISION_INVALID")});
});
