import { describe, expect, it } from "vitest";
import { InMemoryCapabilityCoreRepository, deriveCandidateCapabilityOperand } from "../../../../lib/career/capability-core";
import { buildRequirementRelationAggregate, buildTargetRoleRequirementInventory, InMemoryRequirementInventoryRepository, type T6BPairRepository } from "../../../../lib/career/relation/requirement-inventory";
import { InMemoryRoleRelationRepository, byteReplayRoleRelation, derivationReplayRoleRelation, produceRoleRelation, semanticReplayRoleRelation } from "../../../../lib/career/relation/role-relation";
import { createTargetRoleProfileRevision } from "../../../../lib/career/target/role";
import { createTargetRequirementRevision } from "../../../../lib/career/target/role/requirement";
import { createPhase4Input } from "../../capability-core/relation-operand/phase4-fixture";

const stamp = "2026-10-06T00:00:00.000Z";
const protocol = { relationProducerVersion: "relation-v1", requirementAdmissionPolicyVersion: "admission-v1", semanticPolicyVersion: "semantic-v1", levelPolicyVersion: "level-v1", scopePolicyVersion: "scope-v1", evidencePolicyVersion: "evidence-v1" };
const terminal: T6BPairRepository = { getRelationById: async () => null, getResultById: async () => null, getRunById: async () => null, discoverPairTerminal: async () => ({ disposition: "NOT_EVALUATED" }) };
const lineage = { roleRequirementCoveragePolicyVersion: "coverage-v1", roleDimensionInventoryPolicyVersion: "dimension-v1", roleNecessityPolicyVersion: "necessity-v1", roleCompositionPolicyVersion: "composition-v1" };

async function fixture() {
  const capability = new InMemoryCapabilityCoreRepository();
  const phase4 = createPhase4Input("T7B");
  await capability.saveRun(phase4.discoveryRun); await capability.saveConvergenceRun(phase4.convergenceRun); await capability.saveVerificationRun(phase4.verificationRun);
  const snapshot = await capability.createVerifiedCapabilitySnapshotPublisher().publish(phase4);
  const operand = await deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: snapshot.snapshotId, capabilityId: snapshot.capabilities[0].capabilityId }, capability);
  const profile = createTargetRoleProfileRevision({ targetRoleEntityId: "ROLE_T7B", targetRoleOrganizationBindingRevisionId: "BINDING_T7B", previousRevisionId: null, profile: { roleDescriptor: null, roleSemanticDefinition: "Role", responsibilityScope: null, seniorityInterpretation: null, domainContext: null }, proposalState: "PROPOSAL_ONLY", sourceEvidenceState: "SOURCE_MATCH_VERIFIED", semanticValidationState: "NOT_RUN", authorityState: "NONE", schemaVersion: "TARGET_ROLE_PROFILE_REVISION_V1", createdAt: stamp });
  const requirement = (entity: string, necessity: "REQUIRED" | "PREFERRED") => createTargetRequirementRevision({ targetRequirementEntityId: entity, targetRoleProfileRevisionId: profile.targetRoleProfileRevisionId, previousRevisionId: null, requirement: { normalizedStatement: `${entity} capability`, requirementType: "CAPABILITY", capabilityExpression: "TypeScript", structuralDefinition: "Typed capability", requiredLevelState: { kind: "NOT_APPLICABLE" }, necessityState: { kind: necessity }, scopeContextState: { kind: "NOT_APPLICABLE" } }, evidence: [{ exactQuote: `${entity} capability` }], sourceEvidenceState: "SOURCE_MATCH_VERIFIED", classificationValidationState: "VALIDATED", semanticInterpretationState: "VALIDATED", requiredLevelValidationState: "NOT_APPLICABLE", necessityValidationState: "SUPPORTED", scopeValidationState: "NOT_APPLICABLE", matchingEligibility: "MATCHING_ELIGIBLE_PROPOSAL_ONLY", proposalState: "PROPOSAL_ONLY", authorityState: "NONE", schemaVersion: "TARGET_REQUIREMENT_REVISION_V1", createdAt: stamp });
  const present = requirement("REQ_PRESENT", "REQUIRED"); const absent = requirement("REQ_ABSENT", "PREFERRED");
  const inventory = await buildTargetRoleRequirementInventory({ targetRoleProfileRevisionId: profile.targetRoleProfileRevisionId, requirementInventoryPolicyVersion: "inventory-v1", createdAt: stamp }, { listTargetRequirementRevisionsByTargetRoleProfileRevisionId: async () => [present, absent] });
  const aggregate = await buildRequirementRelationAggregate({ inventory, verifiedCapabilitySnapshotId: snapshot.snapshotId, targetRequirementEntityId: present.targetRequirementEntityId, targetRequirementRevisionId: present.targetRequirementRevisionId, candidateCapabilityOperandIds: [operand.candidateCapabilityOperandId], pairDispositions: [{ candidateCapabilityOperandId: operand.candidateCapabilityOperandId, disposition: "NOT_EVALUATED", capabilityRequirementRelationId: null, capabilityRequirementRelationEvaluationResultId: null }], t6bProtocol: protocol, pairInventoryPolicyVersion: "pair-v1", compositionPolicyVersion: "t7a-composition-v1", createdAt: stamp }, terminal);
  const inventories = new InMemoryRequirementInventoryRepository(); await inventories.persistInventory(inventory); await inventories.persistAggregate(aggregate);
  const roles = new InMemoryRoleRelationRepository();
  return { capability, profile, snapshot, inventory, aggregate, inventories, roles };
}

describe("T7B RoleRelation", () => {
  it("discovers complete exact coverage without provider authority and replays immutable relation state", async () => {
    const value = await fixture(); let providers = 0;
    const role = await produceRoleRelation({ verifiedCapabilitySnapshotId: value.snapshot.snapshotId, targetRoleProfileRevision: value.profile, inventory: value.inventory, createdAt: stamp, lineage }, { aggregates: value.inventories, candidateRepository: value.capability });
    expect(providers).toBe(0);
    expect(role.roleRelationId).toMatch(/^RRL_/); expect(role.proposalState).toBe("PROPOSAL_ONLY"); expect(role.authorityState).toBe("NONE"); expect(role.composition).toEqual({ state: "COMPOSITION_NOT_EVALUATED" });
    expect(role.requirementCoverages.map(value => value.disposition)).toEqual(["NO_AGGREGATE", "DIRECT_CAPABILITY_AGGREGATE_PRESENT"]);
    expect(role.pairTerminalInventory.NOT_EVALUATED.count).toBe(1);
    const later = await produceRoleRelation({ verifiedCapabilitySnapshotId: value.snapshot.snapshotId, targetRoleProfileRevision: value.profile, inventory: value.inventory, createdAt: "2026-10-08T00:00:00.000Z", lineage }, { aggregates: value.inventories, candidateRepository: value.capability });
    expect(later.roleRelationId).toBe(role.roleRelationId);
    await expect(value.roles.persistRoleRelation(role)).resolves.toEqual(role);
    const dependencies = { repository: value.roles, inventories: value.inventories, aggregates: value.inventories, candidateRepository: value.capability, t6b: terminal, getTargetRoleProfileRevisionById: async (id: string) => id === value.profile.targetRoleProfileRevisionId ? value.profile : null, implementations: { resolveRoleRequirementCoveragePolicy: (version: string) => version === "coverage-v1" ? { version } : null, resolveRoleDimensionInventoryPolicy: (version: string) => version === "dimension-v1" ? { version } : null, resolveRoleNecessityPolicy: (version: string) => version === "necessity-v1" ? { version } : null, resolveRoleCompositionPolicy: (version: string) => version === "composition-v1" ? { version } : null } };
    await expect(byteReplayRoleRelation(role.roleRelationId, value.roles)).resolves.toEqual(role);
    await expect(semanticReplayRoleRelation(role.roleRelationId, dependencies)).resolves.toEqual(role);
    await expect(derivationReplayRoleRelation(role.roleRelationId, dependencies)).resolves.toEqual(role);
    await expect(derivationReplayRoleRelation(role.roleRelationId, { ...dependencies, implementations: { ...dependencies.implementations, resolveRoleCompositionPolicy: () => null } })).rejects.toThrow("PINNED_VERSION_UNAVAILABLE");
    await expect(derivationReplayRoleRelation(role.roleRelationId, { ...dependencies, t6b: { ...terminal, discoverPairTerminal: async () => ({ disposition: "MATERIALIZED_RELATION" as const, relation: { capabilityRequirementRelationId: "CRREL_CHANGED" } as any }) } })).rejects.toThrow("DERIVATION_REPLAY_MISMATCH");
    await expect(semanticReplayRoleRelation(role.roleRelationId, { ...dependencies, aggregates: { listAggregatesByExactLocator: async () => [] } })).rejects.toThrow("SEMANTIC_REPLAY_MISMATCH");
    await expect(value.roles.persistRoleRelation({ ...role, proposalState: "PROPOSAL_ONLY", authorityState: "NONE", extra: "unknown" } as any)).rejects.toThrow("ROLE_RELATION_INVALID");
  });

  it("preserves every requirement coverage and necessity state without a role conclusion", async () => {
    const value = await fixture();
    const requirement = (entity: string, necessity: "REQUIRED" | "PREFERRED" | "OPTIONAL" | "CONDITIONAL" | "UNKNOWN", options: { type?: "CAPABILITY" | "RESPONSIBILITY"; eligibility?: "MATCHING_ELIGIBLE_PROPOSAL_ONLY" | "MATCHING_INELIGIBLE" | "MATCHING_ELIGIBILITY_UNKNOWN"; previous?: string | null } = {}) => createTargetRequirementRevision({ targetRequirementEntityId: entity, targetRoleProfileRevisionId: value.profile.targetRoleProfileRevisionId, previousRevisionId: options.previous ?? null, requirement: { normalizedStatement: entity, requirementType: options.type ?? "CAPABILITY", capabilityExpression: options.type === "RESPONSIBILITY" ? null : entity, structuralDefinition: options.type === "RESPONSIBILITY" ? null : `${entity} capability`, requiredLevelState: { kind: "NOT_APPLICABLE" }, necessityState: necessity === "CONDITIONAL" ? { kind: "CONDITIONAL", conditionStatement: "condition remains unevaluated" } : { kind: necessity }, scopeContextState: { kind: "NOT_APPLICABLE" } }, evidence: [{ exactQuote: entity }], sourceEvidenceState: "SOURCE_MATCH_VERIFIED", classificationValidationState: "VALIDATED", semanticInterpretationState: "VALIDATED", requiredLevelValidationState: "NOT_APPLICABLE", necessityValidationState: "SUPPORTED", scopeValidationState: "NOT_APPLICABLE", matchingEligibility: options.eligibility ?? "MATCHING_ELIGIBLE_PROPOSAL_ONLY", proposalState: "PROPOSAL_ONLY", authorityState: "NONE", schemaVersion: "TARGET_REQUIREMENT_REVISION_V1", createdAt: stamp });
    const present = requirement("A_PRESENT", "REQUIRED"); const preferred = requirement("B_PREFERRED", "PREFERRED"); const optional = requirement("C_OPTIONAL", "OPTIONAL"); const conditional = requirement("D_CONDITIONAL", "CONDITIONAL"); const unknown = requirement("E_UNKNOWN", "UNKNOWN"); const nonDirect = requirement("F_NON_DIRECT", "PREFERRED", { type: "RESPONSIBILITY" }); const ineligible = requirement("G_INELIGIBLE", "OPTIONAL", { eligibility: "MATCHING_INELIGIBLE" }); const eligibilityUnknown = requirement("H_ELIGIBILITY_UNKNOWN", "UNKNOWN", { eligibility: "MATCHING_ELIGIBILITY_UNKNOWN" }); const branchOne = requirement("I_BRANCH", "CONDITIONAL"); const branchTwo = requirement("I_BRANCH", "UNKNOWN", { previous: branchOne.targetRequirementRevisionId }); const noAggregate = requirement("J_NO_AGGREGATE", "REQUIRED");
    const inventory = await buildTargetRoleRequirementInventory({ targetRoleProfileRevisionId: value.profile.targetRoleProfileRevisionId, requirementInventoryPolicyVersion: "inventory-v1", createdAt: stamp }, { listTargetRequirementRevisionsByTargetRoleProfileRevisionId: async () => [present, preferred, optional, conditional, unknown, nonDirect, ineligible, eligibilityUnknown, branchOne, branchTwo, noAggregate] });
    const aggregate = await buildRequirementRelationAggregate({ inventory, verifiedCapabilitySnapshotId: value.snapshot.snapshotId, targetRequirementEntityId: present.targetRequirementEntityId, targetRequirementRevisionId: present.targetRequirementRevisionId, candidateCapabilityOperandIds: [await deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: value.snapshot.snapshotId, capabilityId: value.snapshot.capabilities[0].capabilityId }, value.capability).then(operand => operand.candidateCapabilityOperandId)], pairDispositions: [{ candidateCapabilityOperandId: (await deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: value.snapshot.snapshotId, capabilityId: value.snapshot.capabilities[0].capabilityId }, value.capability)).candidateCapabilityOperandId, disposition: "NOT_EVALUATED", capabilityRequirementRelationId: null, capabilityRequirementRelationEvaluationResultId: null }], t6bProtocol: protocol, pairInventoryPolicyVersion: "pair-v1", compositionPolicyVersion: "t7a-composition-v1", createdAt: stamp }, terminal);
    const inventories = new InMemoryRequirementInventoryRepository(); await inventories.persistInventory(inventory); await inventories.persistAggregate(aggregate);
    const role = await produceRoleRelation({ verifiedCapabilitySnapshotId: value.snapshot.snapshotId, targetRoleProfileRevision: value.profile, inventory, createdAt: stamp, lineage }, { aggregates: inventories, candidateRepository: value.capability });
    expect(Object.fromEntries(role.requirementCoverages.map(coverage => [coverage.targetRequirementEntityId, coverage.disposition]))).toEqual({ A_PRESENT: "DIRECT_CAPABILITY_AGGREGATE_PRESENT", B_PREFERRED: "NO_AGGREGATE", C_OPTIONAL: "NO_AGGREGATE", D_CONDITIONAL: "NO_AGGREGATE", E_UNKNOWN: "NO_AGGREGATE", F_NON_DIRECT: "NON_DIRECT_REQUIREMENT", G_INELIGIBLE: "INELIGIBLE", H_ELIGIBILITY_UNKNOWN: "ELIGIBILITY_UNKNOWN", I_BRANCH: "REQUIREMENT_REVISION_BRANCH_UNRESOLVED", J_NO_AGGREGATE: "NO_AGGREGATE" });
    expect(Object.fromEntries(Object.entries(role.necessityInventory).map(([key, entry]) => [key, entry.count]))).toEqual({ REQUIRED: 2, PREFERRED: 2, OPTIONAL: 2, CONDITIONAL: 2, UNKNOWN: 3 });
    expect(role.structuralStateInventory).toContain("REQUIREMENT_REVISION_BRANCH_UNRESOLVED");
    expect(role.composition.state).toBe("COMPOSITION_NOT_EVALUATED");
    const zeroInventory = await buildTargetRoleRequirementInventory({ targetRoleProfileRevisionId: value.profile.targetRoleProfileRevisionId, requirementInventoryPolicyVersion: "inventory-v1", createdAt: stamp }, { listTargetRequirementRevisionsByTargetRoleProfileRevisionId: async () => [] });
    const zero = await produceRoleRelation({ verifiedCapabilitySnapshotId: value.snapshot.snapshotId, targetRoleProfileRevision: value.profile, inventory: zeroInventory, createdAt: stamp, lineage }, { aggregates: inventories, candidateRepository: value.capability });
    expect(zero.structuralStateInventory).toEqual(["NO_REQUIREMENTS"]);
  });

  it("fails closed for foreign operands and preserves multiple exact aggregates as unresolved", async () => {
    const value = await fixture();
    const operand = await deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: value.snapshot.snapshotId, capabilityId: value.snapshot.capabilities[0].capabilityId }, value.capability);
    const second = await buildRequirementRelationAggregate({ inventory: value.inventory, verifiedCapabilitySnapshotId: value.snapshot.snapshotId, targetRequirementEntityId: value.aggregate.targetRequirementEntityId, targetRequirementRevisionId: value.aggregate.targetRequirementRevisionId, candidateCapabilityOperandIds: [operand.candidateCapabilityOperandId], pairDispositions: [{ candidateCapabilityOperandId: operand.candidateCapabilityOperandId, disposition: "NOT_EVALUATED", capabilityRequirementRelationId: null, capabilityRequirementRelationEvaluationResultId: null }], t6bProtocol: protocol, pairInventoryPolicyVersion: "pair-v2", compositionPolicyVersion: "t7a-composition-v1", createdAt: stamp }, terminal);
    await value.inventories.persistAggregate(second);
    const unresolved = await produceRoleRelation({ verifiedCapabilitySnapshotId: value.snapshot.snapshotId, targetRoleProfileRevision: value.profile, inventory: value.inventory, createdAt: stamp, lineage }, { aggregates: value.inventories, candidateRepository: value.capability });
    expect(unresolved.requirementCoverages.find(coverage => coverage.targetRequirementEntityId === value.aggregate.targetRequirementEntityId)?.disposition).toBe("REQUIREMENT_RELATION_AGGREGATE_SET_UNRESOLVED");
    await expect(produceRoleRelation({ verifiedCapabilitySnapshotId: "SNAPSHOT_FOREIGN", targetRoleProfileRevision: value.profile, inventory: value.inventory, createdAt: stamp, lineage }, { aggregates: value.inventories, candidateRepository: value.capability })).rejects.toThrow("OPERAND_MISMATCH");
    const foreignProfile = createTargetRoleProfileRevision({ targetRoleEntityId: "ROLE_FOREIGN", targetRoleOrganizationBindingRevisionId: "BINDING_FOREIGN", previousRevisionId: null, profile: { roleDescriptor: null, roleSemanticDefinition: "Foreign", responsibilityScope: null, seniorityInterpretation: null, domainContext: null }, proposalState: "PROPOSAL_ONLY", sourceEvidenceState: "SOURCE_MATCH_VERIFIED", semanticValidationState: "NOT_RUN", authorityState: "NONE", schemaVersion: "TARGET_ROLE_PROFILE_REVISION_V1", createdAt: stamp });
    await expect(produceRoleRelation({ verifiedCapabilitySnapshotId: value.snapshot.snapshotId, targetRoleProfileRevision: foreignProfile, inventory: value.inventory, createdAt: stamp, lineage }, { aggregates: value.inventories, candidateRepository: value.capability })).rejects.toThrow("OPERAND_MISMATCH");
    const malformedDiscovery = { listAggregatesByExactLocator: async () => [{ ...value.aggregate, verifiedCapabilitySnapshotId: "SNAPSHOT_FOREIGN" }] };
    await expect(produceRoleRelation({ verifiedCapabilitySnapshotId: value.snapshot.snapshotId, targetRoleProfileRevision: value.profile, inventory: value.inventory, createdAt: stamp, lineage }, { aggregates: malformedDiscovery, candidateRepository: value.capability })).rejects.toThrow();
  });
});
