import { createHash } from "node:crypto";
import type { CandidateCapabilityOperand } from "../../capability-core/relation-operand";
import type { TargetRequirementRevision } from "../../target/role/requirement";
import type { CapabilityRequirementRelation, CapabilityRequirementRelationEvaluation, CapabilityRequirementRelationEvaluationResult, CapabilityRequirementRelationEvaluationRun, CapabilityRequirementRelationRawProviderOutputArtifact, CapabilityRequirementRelationProducerLineage, EvidenceSufficiency, LevelRelation, ScopeRelation, SemanticRelation } from "./types";

const fail = (code: string): never => { throw new Error(code); };
const text = (value: unknown): value is string => typeof value === "string" && value.length > 0;
const stamp = (value: unknown): value is string => typeof value === "string" && !Number.isNaN(new Date(value).valueOf()) && new Date(value).toISOString() === value;
const hash = (value: string) => createHash("sha256").update(value, "utf8").digest("hex");
const stable = (value: unknown): string => JSON.stringify(value, (_key, item) => item && typeof item === "object" && !Array.isArray(item) ? Object.fromEntries(Object.keys(item).sort().map(key => [key, (item as Record<string, unknown>)[key]])) : item);
const exact = (value: unknown, keys: string[], code = "ERR_CAPABILITY_REQUIREMENT_RELATION_INVALID"): Record<string, unknown> => { if (!value || typeof value !== "object" || Array.isArray(value)) return fail(code); const item = value as Record<string, unknown>, actual = Object.keys(item).sort(), expected = [...keys].sort(); if (actual.length !== expected.length || actual.some((key, index) => key !== expected[index])) return fail(code); return item; };
const unique = (values: unknown): values is string[] => Array.isArray(values) && values.every(text) && new Set(values).size === values.length;
const semantic = new Set<SemanticRelation>(["SEMANTIC_EQUIVALENT", "SEMANTIC_CANDIDATE_COVERS_REQUIREMENT", "SEMANTIC_PARTIAL", "SEMANTIC_DISTINCT", "SEMANTIC_UNKNOWN"]);
const level = new Set<LevelRelation>(["LEVEL_MEETS", "LEVEL_EXCEEDS", "LEVEL_BELOW", "LEVEL_NOT_COMPARABLE", "LEVEL_NOT_APPLICABLE", "LEVEL_UNKNOWN"]);
const evidence = new Set<EvidenceSufficiency>(["EVIDENCE_SUFFICIENT", "EVIDENCE_INSUFFICIENT", "EVIDENCE_UNKNOWN"]);
const scope = new Set<ScopeRelation>(["SCOPE_COMPATIBLE", "SCOPE_PARTIAL", "SCOPE_INCOMPATIBLE", "SCOPE_NOT_APPLICABLE", "SCOPE_UNKNOWN"]);

function locator(value: unknown): { candidateCapabilityOperandId: string; verifiedCapabilitySnapshotId: string; capabilityId: string } { const x = exact(value, ["candidateCapabilityOperandId", "verifiedCapabilitySnapshotId", "capabilityId"]); if (!text(x.candidateCapabilityOperandId) || !text(x.verifiedCapabilitySnapshotId) || !text(x.capabilityId)) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_INVALID"); return x as { candidateCapabilityOperandId: string; verifiedCapabilitySnapshotId: string; capabilityId: string }; }
function producer(value: unknown): CapabilityRequirementRelationProducerLineage { const x = exact(value, ["relationProducerVersion", "requirementAdmissionPolicyVersion", "semanticPolicyVersion", "levelPolicyVersion", "scopePolicyVersion", "evidencePolicyVersion", "promptChecksum", "provider", "model", "outputSchemaVersion"], "ERR_CAPABILITY_REQUIREMENT_RELATION_ARTIFACT_INVALID"); if (Object.values(x).some(value => !text(value))) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_ARTIFACT_INVALID"); return x as unknown as CapabilityRequirementRelationProducerLineage; }
function evaluation(value: unknown): CapabilityRequirementRelationEvaluation { const x = exact(value, ["semanticRelation", "levelRelation", "evidenceSufficiency", "scopeRelation", "composition", "evidenceBasis"]); if (!semantic.has(x.semanticRelation as SemanticRelation) || !level.has(x.levelRelation as LevelRelation) || !evidence.has(x.evidenceSufficiency as EvidenceSufficiency) || !scope.has(x.scopeRelation as ScopeRelation)) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_INVALID"); const composition = exact(x.composition, ["mode", "state"]); if (composition.mode !== "SINGLE_OPERAND" || composition.state !== "COMPOSITION_NOT_EVALUATED") fail("ERR_CAPABILITY_REQUIREMENT_RELATION_INVALID"); const basis = exact(x.evidenceBasis, ["candidateEvidenceIds", "targetRequirementEvidenceQuotes"]); if (!unique(basis.candidateEvidenceIds) || !unique(basis.targetRequirementEvidenceQuotes)) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_INVALID"); if (x.semanticRelation === "SEMANTIC_DISTINCT" && x.evidenceSufficiency !== "EVIDENCE_SUFFICIENT") fail("ERR_CAPABILITY_REQUIREMENT_RELATION_INVALID"); return { semanticRelation: x.semanticRelation as SemanticRelation, levelRelation: x.levelRelation as LevelRelation, evidenceSufficiency: x.evidenceSufficiency as EvidenceSufficiency, scopeRelation: x.scopeRelation as ScopeRelation, composition: { mode: "SINGLE_OPERAND", state: "COMPOSITION_NOT_EVALUATED" }, evidenceBasis: { candidateEvidenceIds: [...basis.candidateEvidenceIds as string[]], targetRequirementEvidenceQuotes: [...basis.targetRequirementEvidenceQuotes as string[]] } }; }

export function deriveCapabilityRequirementRelationId(value: { operands: CapabilityRequirementRelation["operands"]; lineage: Pick<CapabilityRequirementRelation["lineage"], "relationProducerVersion" | "requirementAdmissionPolicyVersion" | "semanticPolicyVersion" | "levelPolicyVersion" | "scopePolicyVersion" | "evidencePolicyVersion">; schemaVersion: string }): string {
  return `CRREL_${hash(stable(["CAPABILITY_REQUIREMENT_RELATION_V1", value.operands.candidate.candidateCapabilityOperandId, value.operands.targetRequirementRevisionId, value.lineage.relationProducerVersion, value.lineage.requirementAdmissionPolicyVersion, value.lineage.semanticPolicyVersion, value.lineage.levelPolicyVersion, value.lineage.scopePolicyVersion, value.lineage.evidencePolicyVersion, value.schemaVersion])).slice(0, 32).toUpperCase()}`;
}
export const capabilityRequirementRawProviderOutputRef = (raw: string) => `CRRAW_${hash(raw).slice(0, 32).toUpperCase()}`;
export function createCapabilityRequirementRelationRawProviderOutputArtifact(value: Omit<CapabilityRequirementRelationRawProviderOutputArtifact, "rawProviderOutputRef" | "rawProviderOutputHash">): CapabilityRequirementRelationRawProviderOutputArtifact { const item = { rawProviderOutputRef: capabilityRequirementRawProviderOutputRef(value.rawProviderOutput), rawProviderOutputHash: hash(value.rawProviderOutput), ...structuredClone(value) }; assertCapabilityRequirementRelationRawProviderOutputArtifact(item); return structuredClone(item); }
export function assertCapabilityRequirementRelationRawProviderOutputArtifact(value: unknown): asserts value is CapabilityRequirementRelationRawProviderOutputArtifact { const x = exact(value, ["rawProviderOutputRef", "rawProviderOutputHash", "rawProviderOutput", "schemaVersion", "createdAt"], "ERR_CAPABILITY_REQUIREMENT_RELATION_ARTIFACT_INVALID"); if (typeof x.rawProviderOutput !== "string" || x.schemaVersion !== "CAPABILITY_REQUIREMENT_RELATION_RAW_PROVIDER_OUTPUT_V1" || !stamp(x.createdAt) || x.rawProviderOutputHash !== hash(x.rawProviderOutput) || x.rawProviderOutputRef !== capabilityRequirementRawProviderOutputRef(x.rawProviderOutput)) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_ARTIFACT_INVALID"); }
function runInput(value: unknown): Omit<CapabilityRequirementRelationEvaluationRun, "capabilityRequirementRelationEvaluationRunId"> { const x = exact(value, ["candidate", "targetRequirementRevisionId", "producer", "status", "rawProviderOutputRef", "rawProviderOutputHash", "failureCode", "schemaVersion", "startedAt", "completedAt"], "ERR_CAPABILITY_REQUIREMENT_RELATION_ARTIFACT_INVALID"); const status = x.status; if (!text(x.targetRequirementRevisionId) || !["COMPLETED", "PRODUCER_FAILED", "PROVIDER_OUTPUT_INVALID", "VALIDATION_FAILED"].includes(status as string) || x.schemaVersion !== "CAPABILITY_REQUIREMENT_RELATION_EVALUATION_RUN_V1" || !stamp(x.startedAt) || !(x.completedAt === null || stamp(x.completedAt))) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_ARTIFACT_INVALID"); const raw = x.rawProviderOutputRef === null && x.rawProviderOutputHash === null ? null : text(x.rawProviderOutputRef) && typeof x.rawProviderOutputHash === "string" && /^[a-f0-9]{64}$/.test(x.rawProviderOutputHash) ? { ref: x.rawProviderOutputRef, hash: x.rawProviderOutputHash } : fail("ERR_CAPABILITY_REQUIREMENT_RELATION_ARTIFACT_INVALID"); if ((status === "COMPLETED" && (!raw || x.failureCode !== null)) || (status !== "COMPLETED" && (!text(x.failureCode) || x.completedAt === null))) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_ARTIFACT_INVALID"); return { ...(x as Omit<CapabilityRequirementRelationEvaluationRun, "capabilityRequirementRelationEvaluationRunId">), candidate: locator(x.candidate), producer: producer(x.producer) }; }
const runId = (value: Omit<CapabilityRequirementRelationEvaluationRun, "capabilityRequirementRelationEvaluationRunId">) => `CRRUN_${hash(stable([value.candidate, value.targetRequirementRevisionId, value.producer, value.status, value.rawProviderOutputRef, value.rawProviderOutputHash, value.failureCode, value.schemaVersion])).slice(0, 32).toUpperCase()}`;
export function createCapabilityRequirementRelationEvaluationRun(value: Omit<CapabilityRequirementRelationEvaluationRun, "capabilityRequirementRelationEvaluationRunId">): CapabilityRequirementRelationEvaluationRun { const input = runInput(value), run = { capabilityRequirementRelationEvaluationRunId: runId(input), ...input }; assertCapabilityRequirementRelationEvaluationRun(run); return structuredClone(run); }
export function assertCapabilityRequirementRelationEvaluationRun(value: unknown): asserts value is CapabilityRequirementRelationEvaluationRun { const x = exact(value, ["capabilityRequirementRelationEvaluationRunId", "candidate", "targetRequirementRevisionId", "producer", "status", "rawProviderOutputRef", "rawProviderOutputHash", "failureCode", "schemaVersion", "startedAt", "completedAt"], "ERR_CAPABILITY_REQUIREMENT_RELATION_ARTIFACT_INVALID"); const { capabilityRequirementRelationEvaluationRunId, ...input } = x; if (!text(capabilityRequirementRelationEvaluationRunId) || capabilityRequirementRelationEvaluationRunId !== runId(runInput(input))) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_ARTIFACT_INVALID"); }
function resultInput(value: unknown): Omit<CapabilityRequirementRelationEvaluationResult, "capabilityRequirementRelationEvaluationResultId"> { const x = exact(value, ["capabilityRequirementRelationEvaluationRunId", "candidate", "targetRequirementRevisionId", "resultState", "evaluation", "failureCode", "schemaVersion", "createdAt"], "ERR_CAPABILITY_REQUIREMENT_RELATION_ARTIFACT_INVALID"); if (!text(x.capabilityRequirementRelationEvaluationRunId) || !text(x.targetRequirementRevisionId) || !["COMPLETED", "FAILED", "TARGET_REQUIREMENT_INELIGIBLE", "TARGET_REQUIREMENT_ELIGIBILITY_UNKNOWN", "CANDIDATE_OPERAND_INELIGIBLE"].includes(x.resultState as string) || x.schemaVersion !== "CAPABILITY_REQUIREMENT_RELATION_EVALUATION_RESULT_V1" || !stamp(x.createdAt)) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_ARTIFACT_INVALID"); const completed = x.resultState === "COMPLETED"; if ((completed && (x.evaluation === null || x.failureCode !== null)) || (!completed && (x.evaluation !== null || !text(x.failureCode)))) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_ARTIFACT_INVALID"); return { ...(x as Omit<CapabilityRequirementRelationEvaluationResult, "capabilityRequirementRelationEvaluationResultId">), candidate: locator(x.candidate), evaluation: completed ? evaluation(x.evaluation) : null }; }
const resultId = (value: Omit<CapabilityRequirementRelationEvaluationResult, "capabilityRequirementRelationEvaluationResultId">) => `CRRES_${hash(stable([value.capabilityRequirementRelationEvaluationRunId, value.candidate, value.targetRequirementRevisionId, value.resultState, value.evaluation, value.failureCode, value.schemaVersion])).slice(0, 32).toUpperCase()}`;
export function createCapabilityRequirementRelationEvaluationResult(value: Omit<CapabilityRequirementRelationEvaluationResult, "capabilityRequirementRelationEvaluationResultId">): CapabilityRequirementRelationEvaluationResult { const input = resultInput(value), result = { capabilityRequirementRelationEvaluationResultId: resultId(input), ...input }; assertCapabilityRequirementRelationEvaluationResult(result); return structuredClone(result); }
export function assertCapabilityRequirementRelationEvaluationResult(value: unknown): asserts value is CapabilityRequirementRelationEvaluationResult { const x = exact(value, ["capabilityRequirementRelationEvaluationResultId", "capabilityRequirementRelationEvaluationRunId", "candidate", "targetRequirementRevisionId", "resultState", "evaluation", "failureCode", "schemaVersion", "createdAt"], "ERR_CAPABILITY_REQUIREMENT_RELATION_ARTIFACT_INVALID"); const { capabilityRequirementRelationEvaluationResultId, ...input } = x; if (!text(capabilityRequirementRelationEvaluationResultId) || capabilityRequirementRelationEvaluationResultId !== resultId(resultInput(input))) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_ARTIFACT_INVALID"); }
export function createCapabilityRequirementRelation(value: Omit<CapabilityRequirementRelation, "capabilityRequirementRelationId">): CapabilityRequirementRelation { const x = exact(value, ["operands", "evaluation", "evaluationState", "proposalState", "authorityState", "lineage", "schemaVersion", "createdAt"]); const operands = exact(x.operands, ["candidate", "targetRequirementRevisionId"]); const lineage = exact(x.lineage, ["capabilityRequirementRelationEvaluationResultId", "relationProducerVersion", "requirementAdmissionPolicyVersion", "semanticPolicyVersion", "levelPolicyVersion", "scopePolicyVersion", "evidencePolicyVersion"]); if (!text(operands.targetRequirementRevisionId) || !text(lineage.capabilityRequirementRelationEvaluationResultId) || Object.entries(lineage).some(([, value]) => !text(value)) || x.evaluationState !== "COMPLETED" || x.proposalState !== "PROPOSAL_ONLY" || x.authorityState !== "NONE" || x.schemaVersion !== "CAPABILITY_REQUIREMENT_RELATION_V1" || !stamp(x.createdAt)) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_INVALID"); const relation = { capabilityRequirementRelationId: "", operands: { candidate: locator(operands.candidate), targetRequirementRevisionId: operands.targetRequirementRevisionId as string }, evaluation: evaluation(x.evaluation), evaluationState: "COMPLETED" as const, proposalState: "PROPOSAL_ONLY" as const, authorityState: "NONE" as const, lineage: lineage as unknown as CapabilityRequirementRelation["lineage"], schemaVersion: "CAPABILITY_REQUIREMENT_RELATION_V1" as const, createdAt: x.createdAt as string }; relation.capabilityRequirementRelationId = deriveCapabilityRequirementRelationId(relation); return structuredClone(relation); }
export function assertCapabilityRequirementRelation(value: unknown): asserts value is CapabilityRequirementRelation { const x = exact(value, ["capabilityRequirementRelationId", "operands", "evaluation", "evaluationState", "proposalState", "authorityState", "lineage", "schemaVersion", "createdAt"]); const { capabilityRequirementRelationId, ...input } = x; if (!text(capabilityRequirementRelationId) || capabilityRequirementRelationId !== createCapabilityRequirementRelation(input as Omit<CapabilityRequirementRelation, "capabilityRequirementRelationId">).capabilityRequirementRelationId) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_INVALID"); }
export const sameCapabilityRequirementRelationData = (left: unknown, right: unknown) => stable(left) === stable(right);
export const candidateLocatorFromOperand = (operand: CandidateCapabilityOperand) => ({ candidateCapabilityOperandId: operand.candidateCapabilityOperandId, verifiedCapabilitySnapshotId: operand.identity.verifiedCapabilitySnapshotId, capabilityId: operand.identity.capabilityId });
export const targetRequirementEvidenceQuotes = (revision: TargetRequirementRevision) => revision.evidence.map(item => item.exactQuote);
