import { assertCapabilityRequirementRelation, assertCapabilityRequirementRelationEvaluationResult, assertCapabilityRequirementRelationEvaluationRun, assertCapabilityRequirementRelationRawProviderOutputArtifact, sameCapabilityRequirementRelationData } from "./contract";
import type { CapabilityRequirementPairTerminal, CapabilityRequirementRelation, CapabilityRequirementRelationEvaluationResult, CapabilityRequirementRelationEvaluationRun, CapabilityRequirementRelationProtocol, CapabilityRequirementRelationRawProviderOutputArtifact } from "./types";

const fail = (code: string): never => { throw new Error(code); };
function immutable<T>(store: Map<string, T>, id: string, value: T): T { const existing = store.get(id); if (existing !== undefined && !sameCapabilityRequirementRelationData(existing, value)) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_IMMUTABLE_CONFLICT"); if (existing === undefined) store.set(id, structuredClone(value)); return structuredClone(store.get(id)!); }

/** Canonical port: repositories preserve immutable relation artifacts but never grant relation authority. */
export interface CapabilityRequirementRelationRepository {
  getRawProviderOutputByRef(id: string): Promise<CapabilityRequirementRelationRawProviderOutputArtifact | null>;
  getRunById(id: string): Promise<CapabilityRequirementRelationEvaluationRun | null>;
  getResultById(id: string): Promise<CapabilityRequirementRelationEvaluationResult | null>;
  getRelationById(id: string): Promise<CapabilityRequirementRelation | null>;
  persistRawProviderOutput(value: CapabilityRequirementRelationRawProviderOutputArtifact): Promise<CapabilityRequirementRelationRawProviderOutputArtifact>;
  persistRun(value: CapabilityRequirementRelationEvaluationRun): Promise<CapabilityRequirementRelationEvaluationRun>;
  persistResult(value: CapabilityRequirementRelationEvaluationResult): Promise<CapabilityRequirementRelationEvaluationResult>;
  persistRelation(value: CapabilityRequirementRelation): Promise<CapabilityRequirementRelation>;
  discoverPairTerminal(input: { candidateCapabilityOperandId: string; targetRequirementRevisionId: string; protocol: CapabilityRequirementRelationProtocol }): Promise<CapabilityRequirementPairTerminal>;
}

export class InMemoryCapabilityRequirementRelationRepository implements CapabilityRequirementRelationRepository {
  readonly #raw = new Map<string, CapabilityRequirementRelationRawProviderOutputArtifact>();
  readonly #runs = new Map<string, CapabilityRequirementRelationEvaluationRun>();
  readonly #results = new Map<string, CapabilityRequirementRelationEvaluationResult>();
  readonly #relations = new Map<string, CapabilityRequirementRelation>();
  async getRawProviderOutputByRef(id: string) { const value = this.#raw.get(id); if (value === undefined) return null; try { assertCapabilityRequirementRelationRawProviderOutputArtifact(value); return structuredClone(value); } catch { return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); } }
  async getRunById(id: string) { const value = this.#runs.get(id); if (value === undefined) return null; try { assertCapabilityRequirementRelationEvaluationRun(value); return structuredClone(value); } catch { return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); } }
  async getResultById(id: string) { const value = this.#results.get(id); if (value === undefined) return null; try { assertCapabilityRequirementRelationEvaluationResult(value); return structuredClone(value); } catch { return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); } }
  async getRelationById(id: string) { const value = this.#relations.get(id); if (value === undefined) return null; try { assertCapabilityRequirementRelation(value); return structuredClone(value); } catch { return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); } }
  async persistRawProviderOutput(value: CapabilityRequirementRelationRawProviderOutputArtifact) { assertCapabilityRequirementRelationRawProviderOutputArtifact(value); const stored = immutable(this.#raw, value.rawProviderOutputRef, value); const reread = await this.getRawProviderOutputByRef(value.rawProviderOutputRef); if (reread === null || !sameCapabilityRequirementRelationData(reread, stored)) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); return reread!; }
  async persistRun(value: CapabilityRequirementRelationEvaluationRun) { assertCapabilityRequirementRelationEvaluationRun(value); if (value.rawProviderOutputRef !== null) { const raw = await this.getRawProviderOutputByRef(value.rawProviderOutputRef); if (raw === null || raw.rawProviderOutputHash !== value.rawProviderOutputHash) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_RAW_OUTPUT_NOT_FOUND"); } const stored = immutable(this.#runs, value.capabilityRequirementRelationEvaluationRunId, value); const reread = await this.getRunById(value.capabilityRequirementRelationEvaluationRunId); if (reread === null || !sameCapabilityRequirementRelationData(reread, stored)) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); return reread!; }
  async persistResult(value: CapabilityRequirementRelationEvaluationResult) { assertCapabilityRequirementRelationEvaluationResult(value); const run = await this.getRunById(value.capabilityRequirementRelationEvaluationRunId); if (run === null) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_RUN_NOT_FOUND"); if (run.targetRequirementRevisionId !== value.targetRequirementRevisionId || !sameCapabilityRequirementRelationData(run.candidate, value.candidate) || (value.resultState === "COMPLETED") !== (run.status === "COMPLETED")) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); const stored = immutable(this.#results, value.capabilityRequirementRelationEvaluationResultId, value); const reread = await this.getResultById(value.capabilityRequirementRelationEvaluationResultId); if (reread === null || !sameCapabilityRequirementRelationData(reread, stored)) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); return reread!; }
  async persistRelation(value: CapabilityRequirementRelation) { assertCapabilityRequirementRelation(value); const result = await this.getResultById(value.lineage.capabilityRequirementRelationEvaluationResultId); if (result === null || result.resultState !== "COMPLETED" || result.evaluation === null) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_RESULT_NOT_FOUND"); const run = await this.getRunById(result.capabilityRequirementRelationEvaluationRunId); const policyKeys = ["relationProducerVersion", "requirementAdmissionPolicyVersion", "semanticPolicyVersion", "levelPolicyVersion", "scopePolicyVersion", "evidencePolicyVersion"] as const; if (run === null || run.status !== "COMPLETED" || result.targetRequirementRevisionId !== value.operands.targetRequirementRevisionId || !sameCapabilityRequirementRelationData(result.candidate, value.operands.candidate) || !sameCapabilityRequirementRelationData(result.evaluation, value.evaluation) || policyKeys.some(key => value.lineage[key] !== run.producer[key])) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); const stored = immutable(this.#relations, value.capabilityRequirementRelationId, value); const reread = await this.getRelationById(value.capabilityRequirementRelationId); if (reread === null || !sameCapabilityRequirementRelationData(reread, stored)) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); return reread!; }
  async discoverPairTerminal(input: { candidateCapabilityOperandId: string; targetRequirementRevisionId: string; protocol: CapabilityRequirementRelationProtocol }): Promise<CapabilityRequirementPairTerminal> { const keys = ["relationProducerVersion", "requirementAdmissionPolicyVersion", "semanticPolicyVersion", "levelPolicyVersion", "scopePolicyVersion", "evidencePolicyVersion"] as const; const same = (value: any) => keys.every(key => value[key] === input.protocol[key]); const relations = [...this.#relations.values()].filter(value => value.operands.candidate.candidateCapabilityOperandId === input.candidateCapabilityOperandId && value.operands.targetRequirementRevisionId === input.targetRequirementRevisionId && same(value.lineage)); const failures: CapabilityRequirementRelationEvaluationResult[] = []; for (const result of this.#results.values()) { if (result.resultState === "COMPLETED" || result.candidate.candidateCapabilityOperandId !== input.candidateCapabilityOperandId || result.targetRequirementRevisionId !== input.targetRequirementRevisionId) continue; const run = this.#runs.get(result.capabilityRequirementRelationEvaluationRunId); if (run && same(run.producer)) failures.push(result); } if (relations.length + failures.length === 0) return { disposition: "NOT_EVALUATED" }; if (relations.length === 1 && failures.length === 0) return { disposition: "MATERIALIZED_RELATION", relation: structuredClone(relations[0]) }; if (relations.length === 0 && failures.length === 1) return { disposition: "EVALUATION_FAILED", result: structuredClone(failures[0]) }; return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PAIR_CONTRADICTORY"); }
}
