import { assertCandidateCapabilityOperand, type CandidateCapabilityOperand } from "../../capability-core/relation-operand";
import { assertTargetRequirementRevision, type TargetRequirementRevision } from "../../target/role/requirement";
import { assertCapabilityRequirementRelationEvaluationResult, createCapabilityRequirementRelation } from "./contract";
import type { CapabilityRequirementRelation, CapabilityRequirementRelationEvaluationResult, CapabilityRequirementRelationEvaluationRun, CapabilityRequirementRelationProducerLineage } from "./types";
import type { CapabilityRequirementRelationRepository } from "./persistence";

const fail = (code: string): never => { throw new Error(code); };
export interface CapabilityRequirementRelationReplayRepository extends CapabilityRequirementRelationRepository {
  resolveCandidate(input: { verifiedCapabilitySnapshotId: string; capabilityId: string }): Promise<CandidateCapabilityOperand | null>;
  getTargetRequirementRevisionById(id: string): Promise<TargetRequirementRevision | null>;
}
async function operands(relation: CapabilityRequirementRelation, repository: CapabilityRequirementRelationReplayRepository) { const candidate = await repository.resolveCandidate({ verifiedCapabilitySnapshotId: relation.operands.candidate.verifiedCapabilitySnapshotId, capabilityId: relation.operands.candidate.capabilityId }); const target = await repository.getTargetRequirementRevisionById(relation.operands.targetRequirementRevisionId); if (candidate === null || target === null) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_OPERAND_INVALID"); try { assertCandidateCapabilityOperand(candidate); assertTargetRequirementRevision(target); } catch { return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_OPERAND_INVALID"); } if (candidate.candidateCapabilityOperandId !== relation.operands.candidate.candidateCapabilityOperandId || target.targetRequirementRevisionId !== relation.operands.targetRequirementRevisionId) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_OPERAND_INVALID"); return { candidate, target }; }
/** BYTE_REPLAY exact-reads the immutable relation and never recomputes it. */
export async function byteReplayCapabilityRequirementRelation(id: string, repository: CapabilityRequirementRelationReplayRepository): Promise<CapabilityRequirementRelation> { const relation = await repository.getRelationById(id); if (relation === null) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_NOT_FOUND"); return structuredClone(relation); }
/** SEMANTIC_REPLAY uses only persisted result and exact operands; it never calls the provider. */
export async function semanticReplayCapabilityRequirementRelation(id: string, repository: CapabilityRequirementRelationReplayRepository): Promise<CapabilityRequirementRelation> { const historical = await byteReplayCapabilityRequirementRelation(id, repository); const result = await repository.getResultById(historical.lineage.capabilityRequirementRelationEvaluationResultId); if (result === null) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_SEMANTIC_REPLAY_MISMATCH"); if (result.resultState !== "COMPLETED" || result.evaluation === null || result.targetRequirementRevisionId !== historical.operands.targetRequirementRevisionId || result.candidate.candidateCapabilityOperandId !== historical.operands.candidate.candidateCapabilityOperandId || result.candidate.verifiedCapabilitySnapshotId !== historical.operands.candidate.verifiedCapabilitySnapshotId || result.candidate.capabilityId !== historical.operands.candidate.capabilityId) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_SEMANTIC_REPLAY_MISMATCH"); const completed = result as CapabilityRequirementRelationEvaluationResult & { evaluation: NonNullable<CapabilityRequirementRelationEvaluationResult["evaluation"]> }; await operands(historical, repository); const relation = createCapabilityRequirementRelation({ operands: historical.operands, evaluation: completed.evaluation, evaluationState: "COMPLETED", proposalState: "PROPOSAL_ONLY", authorityState: "NONE", lineage: historical.lineage, schemaVersion: "CAPABILITY_REQUIREMENT_RELATION_V1", createdAt: historical.createdAt }); if (relation.capabilityRequirementRelationId !== historical.capabilityRequirementRelationId) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_SEMANTIC_REPLAY_MISMATCH"); return relation; }
/** A replay implementation must explicitly bind every policy that shaped the stored result. */
export interface CapabilityRequirementPinnedDeriver {
  version: string;
  policyVersions: Pick<CapabilityRequirementRelationProducerLineage, "requirementAdmissionPolicyVersion" | "semanticPolicyVersion" | "levelPolicyVersion" | "scopePolicyVersion" | "evidencePolicyVersion">;
  derive(input: { run: CapabilityRequirementRelationEvaluationRun; rawProviderOutput: string; candidate: CandidateCapabilityOperand; target: TargetRequirementRevision }): Promise<CapabilityRequirementRelationEvaluationResult>;
}
/** PROVIDER_AUDIT verifies byte binding only; it makes no provider reproducibility claim. */
export async function providerAuditCapabilityRequirementRelationRun(id: string, repository: CapabilityRequirementRelationReplayRepository): Promise<string> { const run = await repository.getRunById(id); if (run === null) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_RUN_NOT_FOUND"); if (run.rawProviderOutputRef === null || run.rawProviderOutputHash === null) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_RAW_OUTPUT_NOT_FOUND"); const raw = await repository.getRawProviderOutputByRef(run.rawProviderOutputRef); if (raw === null) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_RAW_OUTPUT_NOT_FOUND"); if (raw.rawProviderOutputHash !== run.rawProviderOutputHash) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_RAW_OUTPUT_HASH_MISMATCH"); return raw.rawProviderOutput; }
/** DERIVATION_REPLAY requires the exact stored producer version and never substitutes a current implementation. */
export async function derivationReplayCapabilityRequirementRelation(id: string, repository: CapabilityRequirementRelationReplayRepository, derivers: ReadonlyMap<string, CapabilityRequirementPinnedDeriver>): Promise<CapabilityRequirementRelationEvaluationResult> { const relation = await byteReplayCapabilityRequirementRelation(id, repository); const result = await repository.getResultById(relation.lineage.capabilityRequirementRelationEvaluationResultId); if (result === null) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_RESULT_NOT_FOUND"); const run = await repository.getRunById(result.capabilityRequirementRelationEvaluationRunId); if (run === null) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_DERIVATION_REPLAY_MISMATCH"); if (run.capabilityRequirementRelationEvaluationRunId !== result.capabilityRequirementRelationEvaluationRunId) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_DERIVATION_REPLAY_MISMATCH"); const exactRun = run; const deriver = derivers.get(exactRun.producer.relationProducerVersion); const policyKeys = ["requirementAdmissionPolicyVersion", "semanticPolicyVersion", "levelPolicyVersion", "scopePolicyVersion", "evidencePolicyVersion"] as const; if (!deriver || deriver.version !== exactRun.producer.relationProducerVersion || policyKeys.some(key => deriver.policyVersions[key] !== exactRun.producer[key])) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PINNED_VERSION_UNAVAILABLE"); const exactDeriver = deriver; const { candidate, target } = await operands(relation, repository); const replayed = await exactDeriver.derive({ run: exactRun, rawProviderOutput: await providerAuditCapabilityRequirementRelationRun(exactRun.capabilityRequirementRelationEvaluationRunId, repository), candidate, target }); try { assertCapabilityRequirementRelationEvaluationResult(replayed); } catch { return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_DERIVATION_REPLAY_MISMATCH"); } if (replayed.capabilityRequirementRelationEvaluationResultId !== result.capabilityRequirementRelationEvaluationResultId) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_DERIVATION_REPLAY_MISMATCH"); return structuredClone(replayed); }
