import { describe, expect, it } from "vitest";
import { createTargetRequirementRevision } from "../../../../lib/career/target/role/requirement";
import { buildRequirementRelationAggregate, buildTargetRoleRequirementInventory, type T6BPairRepository } from "../../../../lib/career/relation/requirement-inventory";
import { createCapabilityRequirementRelation, createCapabilityRequirementRelationEvaluationResult, createCapabilityRequirementRelationEvaluationRun } from "../../../../lib/career/relation/capability-requirement";
const stamp="2026-10-01T00:00:00.000Z", protocol={relationProducerVersion:"p",requirementAdmissionPolicyVersion:"a",semanticPolicyVersion:"s",levelPolicyVersion:"l",scopePolicyVersion:"sc",evidencePolicyVersion:"e"};
const req=(entity="REQ",type="CAPABILITY",necessity="REQUIRED",label="")=>createTargetRequirementRevision({targetRequirementEntityId:entity,targetRoleProfileRevisionId:"PROFILE",previousRevisionId:null,requirement:{normalizedStatement:`  statement ${label}`,requirementType:type as any,capabilityExpression:"x",structuralDefinition:"x",requiredLevelState:{kind:"NOT_APPLICABLE"},necessityState:{kind:necessity} as any,scopeContextState:{kind:"NOT_APPLICABLE"}},evidence:[{exactQuote:`  statement ${label}`}],sourceEvidenceState:"SOURCE_MATCH_VERIFIED",classificationValidationState:"VALIDATED",semanticInterpretationState:"VALIDATED",requiredLevelValidationState:"NOT_APPLICABLE",necessityValidationState:"SUPPORTED",scopeValidationState:"NOT_APPLICABLE",matchingEligibility:"MATCHING_ELIGIBLE_PROPOSAL_ONLY",proposalState:"PROPOSAL_ONLY",authorityState:"NONE",schemaVersion:"TARGET_REQUIREMENT_REVISION_V1",createdAt:stamp});
const candidate={candidateCapabilityOperandId:"CCOP_A",verifiedCapabilitySnapshotId:"SNAP",capabilityId:"CAP_A"};
function relation(r:ReturnType<typeof req>){const run=createCapabilityRequirementRelationEvaluationRun({candidate,targetRequirementRevisionId:r.targetRequirementRevisionId,producer:{...protocol,promptChecksum:"x",provider:"x",model:"x",outputSchemaVersion:"x"},status:"COMPLETED",rawProviderOutputRef:"RAW",rawProviderOutputHash:"a".repeat(64),failureCode:null,schemaVersion:"CAPABILITY_REQUIREMENT_RELATION_EVALUATION_RUN_V1",startedAt:stamp,completedAt:stamp});const result=createCapabilityRequirementRelationEvaluationResult({capabilityRequirementRelationEvaluationRunId:run.capabilityRequirementRelationEvaluationRunId,candidate,targetRequirementRevisionId:r.targetRequirementRevisionId,resultState:"COMPLETED",evaluation:{semanticRelation:"SEMANTIC_PARTIAL",levelRelation:"LEVEL_BELOW",evidenceSufficiency:"EVIDENCE_INSUFFICIENT",scopeRelation:"SCOPE_INCOMPATIBLE",composition:{mode:"SINGLE_OPERAND",state:"COMPOSITION_NOT_EVALUATED"},evidenceBasis:{candidateEvidenceIds:["E"],targetRequirementEvidenceQuotes:[r.evidence[0].exactQuote]}},failureCode:null,schemaVersion:"CAPABILITY_REQUIREMENT_RELATION_EVALUATION_RESULT_V1",createdAt:stamp});const value=createCapabilityRequirementRelation({operands:{candidate,targetRequirementRevisionId:r.targetRequirementRevisionId},evaluation:result.evaluation!,evaluationState:"COMPLETED",proposalState:"PROPOSAL_ONLY",authorityState:"NONE",lineage:{capabilityRequirementRelationEvaluationResultId:result.capabilityRequirementRelationEvaluationResultId,...protocol},schemaVersion:"CAPABILITY_REQUIREMENT_RELATION_V1",createdAt:stamp});return {value,result,run}}
describe("T7A requirement inventory",()=>{
 it("groups exact profile revisions without branch selection and preserves direct admission/necessity",async()=>{const a=req("A"),b=req("A","CAPABILITY","REQUIRED","second"),c=req("C","KNOWLEDGE","OPTIONAL");const i=await buildTargetRoleRequirementInventory({targetRoleProfileRevisionId:"PROFILE",requirementInventoryPolicyVersion:"v1",createdAt:stamp},{listTargetRequirementRevisionsByTargetRoleProfileRevisionId:async()=>[c,b,a]});expect(i.requirementGroups.map(x=>x.targetRequirementEntityId)).toEqual(["A","C"]);expect(i.requirementGroups[0].revisionDisposition).toBe("MULTIPLE_REVISIONS_UNRESOLVED");expect(i.requirementGroups[1].directRelationAdmission).toBe("TARGET_REQUIREMENT_TYPE_NOT_DIRECT_CAPABILITY");expect(i.requirementGroups[1].necessityStates[0].necessityState).toBe("OPTIONAL")});
 it("materializes only validated exact pair dispositions and inventories dimensions without a winner",async()=>{const r=req(),i=await buildTargetRoleRequirementInventory({targetRoleProfileRevisionId:"PROFILE",requirementInventoryPolicyVersion:"v1",createdAt:stamp},{listTargetRequirementRevisionsByTargetRoleProfileRevisionId:async()=>[r]}),x=relation(r);const repo:T6BPairRepository={getRelationById:async id=>id===x.value.capabilityRequirementRelationId?x.value:null,getResultById:async()=>null,getRunById:async()=>x.run,discoverPairTerminal:async()=>({disposition:"NOT_EVALUATED" as const})};const a=await buildRequirementRelationAggregate({inventory:i,verifiedCapabilitySnapshotId:"SNAP",targetRequirementEntityId:"REQ",targetRequirementRevisionId:r.targetRequirementRevisionId,candidateCapabilityOperandIds:["CCOP_A"],pairDispositions:[{candidateCapabilityOperandId:"CCOP_A",disposition:"MATERIALIZED_RELATION",capabilityRequirementRelationId:x.value.capabilityRequirementRelationId,capabilityRequirementRelationEvaluationResultId:null}],t6bProtocol:protocol,pairInventoryPolicyVersion:"pair-v1",compositionPolicyVersion:"composition-v1",createdAt:stamp},repo);expect(a.semanticRelationInventory.SEMANTIC_PARTIAL.count).toBe(1);expect(a.levelRelationInventory.LEVEL_BELOW.count).toBe(1);expect(a.composition.state).toBe("COMPOSITION_NOT_EVALUATED");expect(JSON.stringify(a)).not.toMatch(/score|qualified|gap|match/i)});
 it("keeps not evaluated separate and rejects missing, foreign, or mixed pair state",async()=>{const r=req(),i=await buildTargetRoleRequirementInventory({targetRoleProfileRevisionId:"PROFILE",requirementInventoryPolicyVersion:"v1",createdAt:stamp},{listTargetRequirementRevisionsByTargetRoleProfileRevisionId:async()=>[r]}),repo:T6BPairRepository={getRelationById:async()=>null,getResultById:async()=>null,getRunById:async()=>null,discoverPairTerminal:async()=>({disposition:"NOT_EVALUATED" as const})};const base={inventory:i,verifiedCapabilitySnapshotId:"SNAP",targetRequirementEntityId:"REQ",targetRequirementRevisionId:r.targetRequirementRevisionId,candidateCapabilityOperandIds:["CCOP_A"],t6bProtocol:protocol,pairInventoryPolicyVersion:"pair-v1",compositionPolicyVersion:"composition-v1",createdAt:stamp};await expect(buildRequirementRelationAggregate({...base,pairDispositions:[]},repo)).rejects.toThrow("PAIR_INVENTORY_MISMATCH");await expect(buildRequirementRelationAggregate({...base,pairDispositions:[{candidateCapabilityOperandId:"CCOP_A",disposition:"NOT_EVALUATED",capabilityRequirementRelationId:null,capabilityRequirementRelationEvaluationResultId:null}]},repo)).resolves.toMatchObject({pairDispositions:[{disposition:"NOT_EVALUATED"}]})});
});
