import { describe, expect, it } from "vitest";
import * as core from "../../../../lib/career/capability-core";
import * as verification from "../../../../lib/career/capability-core/verification";
import type { CapabilityVerificationIntegrityInput, CapabilityVerificationRun } from "../../../../lib/career/capability-core/verification";
import type { CandidateCapabilityOperandRepository, VerifiedCapabilitySnapshot } from "../../../../lib/career/capability-core";

const stamp = "2026-09-03T00:00:00.000Z";

function phase4Input(key = "A", level: "VERIFIED" | "UNVERIFIED" = "UNVERIFIED"): CapabilityVerificationIntegrityInput {
  const sourceDocuments = [core.createSourceDocument({ docId: `DOC_${key}`, title: `Document ${key}`, rawContent: `Proof ${key}` })];
  const kernelOutput: core.CapabilityKernelOutput = { kernel_version: "discovery-v1", capabilities: [{ canonical_name: "TypeScript", capability_scope: "ATOMIC", structural_definition: "Typed programming capability", primary_domain: "engineering", demonstrated_capability_level: null, model_confidence: 0.9, evidence_mode: "EXPLICIT", evidence: [{ source_document: `DOC_${key}`, location: "source", exact_quote: `Proof ${key}` }] }], coverage_audit: { source_documents_examined: 1, capability_count: 1, atomic_capability_count: 1, composite_capability_count: 0, attribution_pass_completed: true, target_state_ownership_pass_completed: true, atomic_extraction_pass_completed: true, method_capability_pass_completed: true, composite_reconstruction_pass_completed: true, global_convergence_pass_completed: true, inventory_reconciliation_pass_completed: true, final_reconciliation_produced_new_capabilities: false, unresolved_target_operations: 0, segments_classified_as_external_source_content: 0, segments_classified_as_target_subject_operation: 0, segments_classified_as_target_subject_designed_target_state: 0, segments_classified_as_target_organization_capability: 0, segments_excluded_due_to_attribution_ambiguity: 0 } };
  const sourceBundleHash = core.computeSourceBundleHash(sourceDocuments);
  const discoveryRunId = core.buildCapabilityDiscoveryRunId({ sourceBundleHash, kernelVersion: "discovery-v1", promptChecksum: "discovery-prompt", provider: "provider", model: "discovery-model", schemaVersion: "discovery-schema" });
  const candidates = kernelOutput.capabilities.map((item) => core.verifyCandidateEvidence(core.createCapabilityCandidate(discoveryRunId, item), sourceDocuments));
  const discoveryRun: core.CapabilityDiscoveryRun = { runId: discoveryRunId, sourceBundleHash, kernelVersion: "discovery-v1", prompt: { checksum: "discovery-prompt" }, inference: { provider: "provider", model: "discovery-model" }, schemaVersion: "discovery-schema", status: "COMPLETED", rawOutputHash: core.sha256Utf8(core.stableJsonStringify(kernelOutput)), payload: { kernelOutput, candidates, coverageValidation: { status: "PASSED" } }, createdAt: stamp, completedAt: stamp };
  const convergenceOutput = core.validateCapabilityConvergenceOutput({ convergence_version: "convergence-v1", groups: [{ group_key: "typescript", member_candidate_ids: [candidates[0].candidateId], canonical_name: "TypeScript", capability_scope: "ATOMIC", structural_definition: "Typed programming capability", primary_domain: "engineering" }], relations: [], reconciliation_audit: { input_candidate_count: 1, grouped_candidate_count: 1, group_count: 1, same_capability_merge_count: 0, unresolved_relation_count: 0, reconciliation_pass_completed: true } }, candidates);
  const convergenceRunId = core.buildCapabilityConvergenceRunId({ discoveryRunId, discoveryRawOutputHash: discoveryRun.rawOutputHash!, kernelVersion: "convergence-v1", promptChecksum: "convergence-prompt", provider: "provider", model: "convergence-model", schemaVersion: "convergence-schema", algorithmVersion: "convergence-algorithm" });
  const canonical = core.canonicalizeCapabilityConvergence(convergenceOutput, candidates, stamp);
  const convergenceRun: core.CapabilityConvergenceRun = { runKind: "CAPABILITY_CONVERGENCE", convergenceRunId, discoveryRunId, discoveryRawOutputHash: discoveryRun.rawOutputHash!, sourceBundleHash, kernelVersion: "convergence-v1", prompt: { checksum: "convergence-prompt" }, inference: { provider: "provider", model: "convergence-model" }, schemaVersion: "convergence-schema", algorithmVersion: "convergence-algorithm", status: "COMPLETED", rawOutputHash: core.sha256Utf8(core.stableConvergenceJsonStringify(convergenceOutput)), payload: { convergenceOutput, canonicalDrafts: canonical.canonicalDrafts, proposedRelations: canonical.proposedRelations, eligibleCandidateIds: [candidates[0].candidateId], excludedCandidateIds: [], reconciliation: { status: "PASSED" } }, createdAt: stamp, completedAt: stamp };
  const payload: CapabilityVerificationRun["payload"] = { semanticDefinitionOutcomes: [{ provisionalCapabilityId: canonical.canonicalDrafts[0].provisionalCapabilityId, status: "PASSED" }], demonstratedLevelOutcomes: [{ provisionalCapabilityId: canonical.canonicalDrafts[0].provisionalCapabilityId, status: level, demonstratedCapabilityLevel: level === "VERIFIED" ? "L3" : null }], relationDispositions: [], publicationEligibility: "ELIGIBLE" };
  const verificationRun: CapabilityVerificationRun = { runKind: "CAPABILITY_VERIFICATION", verificationRunId: "", convergenceRunId, convergenceRawOutputHash: convergenceRun.rawOutputHash, sourceEvidenceRepresentationHash: verification.computeSourceEvidenceRepresentationHash(sourceDocuments), sourceBundleHash, kernelVersion: "verification-v1", promptChecksum: "verification-prompt", inference: { provider: "provider", model: "verification-model" }, schemaVersion: "verification-schema", algorithmVersion: "verification-algorithm", snapshotSchemaVersion: "snapshot-schema", rawOutputHash: verification.computeCapabilityVerificationRawOutputHash(payload), status: "COMPLETED", payload, createdAt: stamp, completedAt: stamp };
  verificationRun.verificationRunId = verification.buildCapabilityVerificationRunId({ convergenceRunId, convergenceRawOutputHash: verificationRun.convergenceRawOutputHash, sourceEvidenceRepresentationHash: verificationRun.sourceEvidenceRepresentationHash, kernelVersion: verificationRun.kernelVersion, promptChecksum: verificationRun.promptChecksum, provider: verificationRun.inference.provider, model: verificationRun.inference.model, schemaVersion: verificationRun.schemaVersion, algorithmVersion: verificationRun.algorithmVersion, snapshotSchemaVersion: verificationRun.snapshotSchemaVersion });
  return { sourceDocuments, discoveryRun, convergenceRun, verificationRun };
}

async function publish(key = "A", level: "VERIFIED" | "UNVERIFIED" = "UNVERIFIED") { const repository = new core.InMemoryCapabilityCoreRepository(); const input = phase4Input(key, level); await repository.saveRun(input.discoveryRun); await repository.saveConvergenceRun(input.convergenceRun); await repository.saveVerificationRun(input.verificationRun); const snapshot = await repository.createVerifiedCapabilitySnapshotPublisher().publish(input); return { repository, input, snapshot, capabilityId: snapshot.capabilities[0].capabilityId }; }
const source = (snapshot: VerifiedCapabilitySnapshot, run: CapabilityVerificationRun): CandidateCapabilityOperandRepository => ({ getSnapshotById: async () => structuredClone(snapshot), getVerificationRunById: async () => structuredClone(run) });

describe("T6A Candidate Capability Operand", () => {
  it("derives an exact relation operand only from the authenticated Phase-4 publisher boundary", async () => { const x = await publish(); const operand = await core.deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: x.snapshot.snapshotId, capabilityId: x.capabilityId }, x.repository); expect(operand).toMatchObject({ candidateCapabilityOperandId: expect.stringMatching(/^CCOP_[A-F0-9]{32}$/), identity: { verifiedCapabilitySnapshotId: x.snapshot.snapshotId, capabilityId: x.capabilityId }, source: { sourceBundleHash: x.snapshot.sourceBundleHash, evidenceIds: x.snapshot.capabilities[0].evidenceIds, sourceDocumentIds: x.snapshot.capabilities[0].provenance.sourceDocumentIds }, validation: { evidenceState: "VERIFIED", semanticDefinitionState: "PASSED", convergenceState: "VERIFIED", levelVerificationState: "UNVERIFIED" }, authority: { publicationState: "PHASE4_VERIFIED", relationEligibilityState: "RELATION_ELIGIBLE" }, lineage: { verificationRunId: x.input.verificationRun.verificationRunId, verificationRawOutputHash: x.input.verificationRun.rawOutputHash } }); });
  it("is deterministic for one exact source and differs for the same capability under a different Phase-4 snapshot", async () => { const a = await publish("A"), b = await publish("B"); const first = await core.deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: a.snapshot.snapshotId, capabilityId: a.capabilityId }, a.repository); const replay = await core.deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: a.snapshot.snapshotId, capabilityId: a.capabilityId }, a.repository); const other = await core.deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: b.snapshot.snapshotId, capabilityId: b.capabilityId }, b.repository); expect(replay).toEqual(first); expect(other.identity.capabilityId).toBe(first.identity.capabilityId); expect(other.candidateCapabilityOperandId).not.toBe(first.candidateCapabilityOperandId); });
  it.each([
    ["generic draft", (snapshot: VerifiedCapabilitySnapshot) => ({ ...snapshot, status: "DRAFT" as const, publication: undefined })],
    ["generic verified", (snapshot: VerifiedCapabilitySnapshot) => ({ ...snapshot, publication: undefined })],
    ["invalid semantic", (snapshot: VerifiedCapabilitySnapshot) => ({ ...snapshot, capabilities: [{ ...snapshot.capabilities[0], validation: { ...snapshot.capabilities[0].validation, semanticDefinitionStatus: "NOT_RUN" as const } }] })],
    ["invalid evidence", (snapshot: VerifiedCapabilitySnapshot) => ({ ...snapshot, capabilities: [{ ...snapshot.capabilities[0], validation: { ...snapshot.capabilities[0].validation, evidenceStatus: "PASSED" as const }, evidenceIds: [] }], capabilityIds: [snapshot.capabilities[0].capabilityId] })],
    ["invalid convergence", (snapshot: VerifiedCapabilitySnapshot) => ({ ...snapshot, capabilities: [{ ...snapshot.capabilities[0], validation: { ...snapshot.capabilities[0].validation, convergenceStatus: "MANUAL_GOLD" as const } }] })],
    ["duplicate capability", (snapshot: VerifiedCapabilitySnapshot) => ({ ...snapshot, capabilities: [snapshot.capabilities[0], structuredClone(snapshot.capabilities[0])], capabilityIds: [snapshot.capabilities[0].capabilityId, snapshot.capabilities[0].capabilityId] })]
  ] as const)("fails closed for %s source state", async (_name, mutate) => { const x = await publish(); await expect(core.deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: x.snapshot.snapshotId, capabilityId: x.capabilityId }, source(mutate(x.snapshot), x.input.verificationRun))).rejects.toThrow(); });
  it("rejects missing capability, mismatched verification lineage, and caller authority tokens", async () => { const x = await publish(); await expect(core.deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: x.snapshot.snapshotId, capabilityId: "CAP_MISSING" }, x.repository)).rejects.toThrow("ERR_CANDIDATE_CAPABILITY_OPERAND_CAPABILITY_NOT_FOUND"); await expect(core.deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: x.snapshot.snapshotId, capabilityId: x.capabilityId }, source(x.snapshot, { ...x.input.verificationRun, rawOutputHash: "0".repeat(64) }))).rejects.toThrow(); await expect(core.deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: x.snapshot.snapshotId, capabilityId: x.capabilityId, publicationState: "PHASE4_VERIFIED", evidenceState: "VERIFIED" } as any, x.repository)).resolves.toMatchObject({ authority: { publicationState: "PHASE4_VERIFIED" } }); });
  it("preserves verified and unverified level truth without treating unverified level as relation ineligibility", async () => { const verified = await publish("LEVEL_VERIFIED", "VERIFIED"), unverified = await publish("LEVEL_UNVERIFIED", "UNVERIFIED"); const a = await core.deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: verified.snapshot.snapshotId, capabilityId: verified.capabilityId }, verified.repository); const b = await core.deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: unverified.snapshot.snapshotId, capabilityId: unverified.capabilityId }, unverified.repository); expect(a.validation.levelVerificationState).toBe("VERIFIED"); expect(a.capability.demonstratedCapabilityLevel).toBe("L3"); expect(b.validation.levelVerificationState).toBe("UNVERIFIED"); expect(b.capability.demonstratedCapabilityLevel).toBeNull(); expect(b.authority.relationEligibilityState).toBe("RELATION_ELIGIBLE"); });
  it("replays from a fresh exact repository surface without provider invocation or relation-result fields", async () => { const x = await publish(); const fresh: CandidateCapabilityOperandRepository = { getSnapshotById: x.repository.getSnapshotById.bind(x.repository), getVerificationRunById: x.repository.getVerificationRunById.bind(x.repository) }; const first = await core.deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: x.snapshot.snapshotId, capabilityId: x.capabilityId }, fresh); const replay = await core.deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: x.snapshot.snapshotId, capabilityId: x.capabilityId }, fresh); expect(replay.candidateCapabilityOperandId).toBe(first.candidateCapabilityOperandId); expect(Object.keys(first).sort()).toEqual(["authority", "candidateCapabilityOperandId", "capability", "identity", "lineage", "schemaVersion", "source", "validation"]); expect(JSON.stringify(first)).not.toMatch(/matched|qualified|missing|gap|recommendation|decision|resonance/i); });
  it("keeps identity stable across a snapshot audit timestamp change but fails closed for source inventory mutation", async () => { const x = await publish(); const replaySource = source({ ...x.snapshot, createdAt: "2030-01-01T00:00:00.000Z" }, x.input.verificationRun); const first = await core.deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: x.snapshot.snapshotId, capabilityId: x.capabilityId }, x.repository); const replay = await core.deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: x.snapshot.snapshotId, capabilityId: x.capabilityId }, replaySource); expect(replay.candidateCapabilityOperandId).toBe(first.candidateCapabilityOperandId); const corrupt = { ...x.snapshot, capabilities: [{ ...x.snapshot.capabilities[0], provenance: { ...x.snapshot.capabilities[0].provenance, sourceDocumentIds: ["DOC_FORGED"] } }] }; await expect(core.deriveCandidateCapabilityOperand({ verifiedCapabilitySnapshotId: x.snapshot.snapshotId, capabilityId: x.capabilityId }, source(corrupt, x.input.verificationRun))).rejects.toThrow("ERR_CANDIDATE_CAPABILITY_OPERAND_EVIDENCE_INVENTORY_INVALID"); });
});
