import * as core from "../../../../lib/career/capability-core";
import * as verification from "../../../../lib/career/capability-core/verification";
import type { CapabilityVerificationIntegrityInput, CapabilityVerificationRun } from "../../../../lib/career/capability-core/verification";

export const phase4FixtureStamp = "2026-09-03T00:00:00.000Z";

/** Real Phase-4 publisher input: no provider is involved in fixture construction or operand replay. */
export function createPhase4Input(key = "A", level: "VERIFIED" | "UNVERIFIED" = "UNVERIFIED"): CapabilityVerificationIntegrityInput {
  const sourceDocuments = [core.createSourceDocument({ docId: `DOC_${key}`, title: `Document ${key}`, rawContent: `Proof ${key}` })];
  const kernelOutput: core.CapabilityKernelOutput = { kernel_version: "discovery-v1", capabilities: [{ canonical_name: "TypeScript", capability_scope: "ATOMIC", structural_definition: "Typed programming capability", primary_domain: "engineering", demonstrated_capability_level: null, model_confidence: 0.9, evidence_mode: "EXPLICIT", evidence: [{ source_document: `DOC_${key}`, location: "source", exact_quote: `Proof ${key}` }] }], coverage_audit: { source_documents_examined: 1, capability_count: 1, atomic_capability_count: 1, composite_capability_count: 0, attribution_pass_completed: true, target_state_ownership_pass_completed: true, atomic_extraction_pass_completed: true, method_capability_pass_completed: true, composite_reconstruction_pass_completed: true, global_convergence_pass_completed: true, inventory_reconciliation_pass_completed: true, final_reconciliation_produced_new_capabilities: false, unresolved_target_operations: 0, segments_classified_as_external_source_content: 0, segments_classified_as_target_subject_operation: 0, segments_classified_as_target_subject_designed_target_state: 0, segments_classified_as_target_organization_capability: 0, segments_excluded_due_to_attribution_ambiguity: 0 } };
  const sourceBundleHash = core.computeSourceBundleHash(sourceDocuments); const discoveryRunId = core.buildCapabilityDiscoveryRunId({ sourceBundleHash, kernelVersion: "discovery-v1", promptChecksum: "discovery-prompt", provider: "provider", model: "discovery-model", schemaVersion: "discovery-schema" }); const candidates = kernelOutput.capabilities.map((item) => core.verifyCandidateEvidence(core.createCapabilityCandidate(discoveryRunId, item), sourceDocuments));
  const discoveryRun: core.CapabilityDiscoveryRun = { runId: discoveryRunId, sourceBundleHash, kernelVersion: "discovery-v1", prompt: { checksum: "discovery-prompt" }, inference: { provider: "provider", model: "discovery-model" }, schemaVersion: "discovery-schema", status: "COMPLETED", rawOutputHash: core.sha256Utf8(core.stableJsonStringify(kernelOutput)), payload: { kernelOutput, candidates, coverageValidation: { status: "PASSED" } }, createdAt: phase4FixtureStamp, completedAt: phase4FixtureStamp };
  const convergenceOutput = core.validateCapabilityConvergenceOutput({ convergence_version: "convergence-v1", groups: [{ group_key: "typescript", member_candidate_ids: [candidates[0].candidateId], canonical_name: "TypeScript", capability_scope: "ATOMIC", structural_definition: "Typed programming capability", primary_domain: "engineering" }], relations: [], reconciliation_audit: { input_candidate_count: 1, grouped_candidate_count: 1, group_count: 1, same_capability_merge_count: 0, unresolved_relation_count: 0, reconciliation_pass_completed: true } }, candidates); const canonical = core.canonicalizeCapabilityConvergence(convergenceOutput, candidates, phase4FixtureStamp); const convergenceRunId = core.buildCapabilityConvergenceRunId({ discoveryRunId, discoveryRawOutputHash: discoveryRun.rawOutputHash!, kernelVersion: "convergence-v1", promptChecksum: "convergence-prompt", provider: "provider", model: "convergence-model", schemaVersion: "convergence-schema", algorithmVersion: "convergence-algorithm" });
  const convergenceRun: core.CapabilityConvergenceRun = { runKind: "CAPABILITY_CONVERGENCE", convergenceRunId, discoveryRunId, discoveryRawOutputHash: discoveryRun.rawOutputHash!, sourceBundleHash, kernelVersion: "convergence-v1", prompt: { checksum: "convergence-prompt" }, inference: { provider: "provider", model: "convergence-model" }, schemaVersion: "convergence-schema", algorithmVersion: "convergence-algorithm", status: "COMPLETED", rawOutputHash: core.sha256Utf8(core.stableConvergenceJsonStringify(convergenceOutput)), payload: { convergenceOutput, canonicalDrafts: canonical.canonicalDrafts, proposedRelations: canonical.proposedRelations, eligibleCandidateIds: [candidates[0].candidateId], excludedCandidateIds: [], reconciliation: { status: "PASSED" } }, createdAt: phase4FixtureStamp, completedAt: phase4FixtureStamp };
  const payload: CapabilityVerificationRun["payload"] = { semanticDefinitionOutcomes: [{ provisionalCapabilityId: canonical.canonicalDrafts[0].provisionalCapabilityId, status: "PASSED" }], demonstratedLevelOutcomes: [{ provisionalCapabilityId: canonical.canonicalDrafts[0].provisionalCapabilityId, status: level, demonstratedCapabilityLevel: level === "VERIFIED" ? "L3" : null }], relationDispositions: [], publicationEligibility: "ELIGIBLE" };
  const verificationRun: CapabilityVerificationRun = { runKind: "CAPABILITY_VERIFICATION", verificationRunId: "", convergenceRunId, convergenceRawOutputHash: convergenceRun.rawOutputHash, sourceEvidenceRepresentationHash: verification.computeSourceEvidenceRepresentationHash(sourceDocuments), sourceBundleHash, kernelVersion: "verification-v1", promptChecksum: "verification-prompt", inference: { provider: "provider", model: "verification-model" }, schemaVersion: "verification-schema", algorithmVersion: "verification-algorithm", snapshotSchemaVersion: "snapshot-schema", rawOutputHash: verification.computeCapabilityVerificationRawOutputHash(payload), status: "COMPLETED", payload, createdAt: phase4FixtureStamp, completedAt: phase4FixtureStamp };
  verificationRun.verificationRunId = verification.buildCapabilityVerificationRunId({ convergenceRunId, convergenceRawOutputHash: verificationRun.convergenceRawOutputHash, sourceEvidenceRepresentationHash: verificationRun.sourceEvidenceRepresentationHash, kernelVersion: verificationRun.kernelVersion, promptChecksum: verificationRun.promptChecksum, provider: verificationRun.inference.provider, model: verificationRun.inference.model, schemaVersion: verificationRun.schemaVersion, algorithmVersion: verificationRun.algorithmVersion, snapshotSchemaVersion: verificationRun.snapshotSchemaVersion });
  return { sourceDocuments, discoveryRun, convergenceRun, verificationRun };
}
