import { jsonb, pgTable, text } from "drizzle-orm/pg-core";
import { careerCapabilitySnapshots } from "../../db/schema";
import { targetRoleProfileRevisions } from "../../target-adapters/role-profile-revision-persistence/postgres-schema";
import { targetRequirementRevisions } from "../../target-adapters/role-requirement-revision-persistence/postgres-schema";
import { capabilityRequirementRelationEvaluationResults, capabilityRequirementRelations } from "../capability-requirement-persistence/postgres-schema";
import type { RequirementRelationAggregate, TargetRoleRequirementInventory } from "../../relation/requirement-inventory";

/** FKs preserve immutable artifact lineage only; PostgreSQL does not decide relation meaning. */
export const targetRoleRequirementInventories=pgTable("target_role_requirement_inventories",{targetRoleRequirementInventoryId:text("target_role_requirement_inventory_id").primaryKey(),targetRoleProfileRevisionId:text("target_role_profile_revision_id").notNull().references(()=>targetRoleProfileRevisions.targetRoleProfileRevisionId,{onDelete:"restrict"}),payload:jsonb("payload").$type<TargetRoleRequirementInventory>().notNull()});
export const requirementRelationAggregates=pgTable("requirement_relation_aggregates",{requirementRelationAggregateId:text("requirement_relation_aggregate_id").primaryKey(),targetRoleRequirementInventoryId:text("target_role_requirement_inventory_id").notNull().references(()=>targetRoleRequirementInventories.targetRoleRequirementInventoryId,{onDelete:"restrict"}),verifiedCapabilitySnapshotId:text("verified_capability_snapshot_id").notNull().references(()=>careerCapabilitySnapshots.snapshotId,{onDelete:"restrict"}),targetRequirementRevisionId:text("target_requirement_revision_id").notNull().references(()=>targetRequirementRevisions.targetRequirementRevisionId,{onDelete:"restrict"}),payload:jsonb("payload").$type<RequirementRelationAggregate>().notNull()});
export const requirementRelationAggregateMaterializedRelations=pgTable("requirement_relation_aggregate_materialized_relations",{referenceId:text("reference_id").primaryKey(),requirementRelationAggregateId:text("requirement_relation_aggregate_id").notNull().references(()=>requirementRelationAggregates.requirementRelationAggregateId,{onDelete:"restrict"}),candidateCapabilityOperandId:text("candidate_capability_operand_id").notNull(),capabilityRequirementRelationId:text("capability_requirement_relation_id").notNull().references(()=>capabilityRequirementRelations.capabilityRequirementRelationId,{onDelete:"restrict"})});
export const requirementRelationAggregateFailedResults=pgTable("requirement_relation_aggregate_failed_results",{referenceId:text("reference_id").primaryKey(),requirementRelationAggregateId:text("requirement_relation_aggregate_id").notNull().references(()=>requirementRelationAggregates.requirementRelationAggregateId,{onDelete:"restrict"}),candidateCapabilityOperandId:text("candidate_capability_operand_id").notNull(),capabilityRequirementRelationEvaluationResultId:text("capability_requirement_relation_evaluation_result_id").notNull().references(()=>capabilityRequirementRelationEvaluationResults.capabilityRequirementRelationEvaluationResultId,{onDelete:"restrict"})});
export const requirementRelationAggregateNotEvaluatedPairs=pgTable("requirement_relation_aggregate_not_evaluated_pairs",{referenceId:text("reference_id").primaryKey(),requirementRelationAggregateId:text("requirement_relation_aggregate_id").notNull().references(()=>requirementRelationAggregates.requirementRelationAggregateId,{onDelete:"restrict"}),candidateCapabilityOperandId:text("candidate_capability_operand_id").notNull(),targetRequirementRevisionId:text("target_requirement_revision_id").notNull().references(()=>targetRequirementRevisions.targetRequirementRevisionId,{onDelete:"restrict"})});
