import { describe, expect, it } from "vitest";
import {
  ActivePromptCapabilityKernelResolver, InMemoryCapabilityCoreRepository, assertCapabilityCoverageAudit,
  buildCapabilityDiscoveryPrompt, buildCapabilityDiscoveryRunId, computeSourceBundleHash, createSourceDocument, createVerifiedCapabilitySnapshot,
  GeminiCapabilityDiscoveryProvider, runCapabilityDiscovery, type CapabilityDiscoveryProvider, type CapabilityKernelOutput, type EvidenceClaim, type VerifiedCapability
} from "../../../../lib/career/capability-core";

const marker = "ULTRA_SECRET_FAKE_KERNEL_MARKER_92F1";
const audit = (count = 1) => ({ source_documents_examined: 1, capability_count: count, atomic_capability_count: count, composite_capability_count: 0, attribution_pass_completed: true, target_state_ownership_pass_completed: true, atomic_extraction_pass_completed: true, method_capability_pass_completed: true, composite_reconstruction_pass_completed: true, global_convergence_pass_completed: true, inventory_reconciliation_pass_completed: true, final_reconciliation_produced_new_capabilities: false, unresolved_target_operations: 0, segments_classified_as_external_source_content: 0, segments_classified_as_target_subject_operation: 0, segments_classified_as_target_subject_designed_target_state: 0, segments_classified_as_target_organization_capability: 0, segments_excluded_due_to_attribution_ambiguity: 0 });
const output = (quote = "Literal proof.", kernel = "v"): CapabilityKernelOutput => ({ kernel_version: kernel, capabilities: [{ canonical_name: "Discovery", capability_scope: "ATOMIC", structural_definition: "D", primary_domain: null, demonstrated_capability_level: null, model_confidence: 1, evidence_mode: "EXPLICIT", evidence: [{ source_document: "D", location: "section", exact_quote: quote }] }], coverage_audit: audit() });
const doc = createSourceDocument({ docId: "D", title: "Title", rawContent: "Literal proof." });
const resolver = { resolve: async () => ({ kernelVersion: "v", templateId: "T", versionId: "V", checksum: "C", plainTextContent: marker }) };
const provider = (result = output()): CapabilityDiscoveryProvider => ({ providerName: "mock", model: "model-1", execute: async () => ({ kernelOutput: result }) });
const identity = { sourceBundleHash: "source", kernelVersion: "kernel", promptChecksum: "checksum", provider: "provider", model: "model", schemaVersion: "schema" };

describe("Phase 2 explicit behavioral matrix", () => {
  it.each([
    ["metadata mapping", "T", "V", "C"], ["slug forwarding", "T", "V", "C"], ["explicit key forwarding", "T", "V", "C"]
  ])("prompt resolver: %s", async (_name, templateId, versionId, checksum) => {
    let args: unknown[] = []; const active = { resolveActivePrompt: async (...received: unknown[]) => { args = received; return { templateId, versionId, checksum, plainTextContent: marker }; } };
    const resolved = await new ActivePromptCapabilityKernelResolver(active as never, "capability-kernel", "owned-kernel", "KEY").resolve();
    expect(resolved).toMatchObject({ templateId, versionId, checksum, kernelVersion: "owned-kernel", plainTextContent: marker }); expect(args).toEqual(["capability-kernel", "KEY"]);
  });
  it.each([
    ["documents sorted", (p: string) => p.indexOf("DOC_ID: A") < p.indexOf("DOC_ID: B")], ["pages numeric", (p: string) => p.indexOf("<PAGE number=\"1\">") < p.indexOf("<PAGE number=\"2\">")], ["paged source not duplicated", (p: string) => p.split("Page two").length - 1 === 1], ["unpaged source once", (p: string) => p.split("Once.").length - 1 === 1], ["arrival order independent", (p: string) => p.indexOf("DOC_ID: A") < p.indexOf("DOC_ID: B")], ["punctuation case order preserved", (p: string) => p.includes("Once.")]
  ])("prompt builder: %s", (_name, assertion) => { const a = createSourceDocument({ docId: "A", title: "A", rawContent: "Once." }); const b = createSourceDocument({ docId: "B", title: "B", rawContent: "Ignored", pages: [{ pageNumber: 2, text: "Page two" }, { pageNumber: 1, text: "Page one" }] }); const prompt = buildCapabilityDiscoveryPrompt([b, a], resolver as never).userPrompt; expect(assertion(prompt)).toBe(true); });
  it.each([["valid counts", 1, 1, 1], ["source mismatch", 2, 1, 1], ["total mismatch", 1, 2, 1], ["atomic mismatch", 1, 1, 2], ["composite mismatch", 1, 1, 0]])("coverage: %s", (_name, source, total, atomic) => { const value = output(); value.coverage_audit.source_documents_examined = source; value.coverage_audit.capability_count = total; value.coverage_audit.atomic_capability_count = atomic; if (_name === "valid counts") expect(() => assertCapabilityCoverageAudit(value, 1)).not.toThrow(); else expect(() => assertCapabilityCoverageAudit(value, 1)).toThrow(/COVERAGE/); });
  it.each([["same identity", identity, identity], ["source changes ID", identity, { ...identity, sourceBundleHash: "changed" }], ["checksum changes ID", identity, { ...identity, promptChecksum: "changed" }], ["model changes ID", identity, { ...identity, model: "changed" }], ["provider changes ID", identity, { ...identity, provider: "changed" }], ["schema changes ID", identity, { ...identity, schemaVersion: "changed" }], ["kernel changes ID", identity, { ...identity, kernelVersion: "changed" }]])("run identity: %s", (_name, left, right) => { if (_name === "same identity") expect(buildCapabilityDiscoveryRunId(left)).toBe(buildCapabilityDiscoveryRunId(right)); else expect(buildCapabilityDiscoveryRunId(left)).not.toBe(buildCapabilityDiscoveryRunId(right)); });
  it.each([
    ["valid output creates candidates", async () => { const r = await runCapabilityDiscovery([doc], { kernelVersion: "v", schemaVersion: "1" }, { kernelResolver: resolver, provider: provider(), repository: new InMemoryCapabilityCoreRepository() }); expect((r as any).run.payload.candidates).toHaveLength(1); }],
    ["verified quote passes evidence", async () => { const r = await runCapabilityDiscovery([doc], { kernelVersion: "v", schemaVersion: "1" }, { kernelResolver: resolver, provider: provider(), repository: new InMemoryCapabilityCoreRepository() }); expect((r as any).run.payload.candidates[0].status).toBe("EVIDENCE_PASSED"); }],
    ["fake quote rejects evidence", async () => { const r = await runCapabilityDiscovery([doc], { kernelVersion: "v", schemaVersion: "1" }, { kernelResolver: resolver, provider: provider(output("fake")), repository: new InMemoryCapabilityCoreRepository() }); expect((r as any).run.payload.candidates[0].status).toBe("EVIDENCE_REJECTED"); }],
    ["resolver mismatch before inference", async () => { await expect(runCapabilityDiscovery([doc], { kernelVersion: "wrong", schemaVersion: "1" }, { kernelResolver: resolver, provider: { ...provider(), execute: async () => { throw new Error("called"); } }, repository: new InMemoryCapabilityCoreRepository() })).rejects.toThrow(/KERNEL_VERSION/); }],
    ["model output mismatch", async () => { await expect(runCapabilityDiscovery([doc], { kernelVersion: "v", schemaVersion: "1" }, { kernelResolver: resolver, provider: provider(output("Literal proof.", "wrong")), repository: new InMemoryCapabilityCoreRepository() })).rejects.toThrow(/KERNEL_VERSION/); }],
    ["coverage mismatch before persistence", async () => { const bad = output(); bad.coverage_audit.capability_count = 9; const repo = new InMemoryCapabilityCoreRepository(); await expect(runCapabilityDiscovery([doc], { kernelVersion: "v", schemaVersion: "1" }, { kernelResolver: resolver, provider: provider(bad), repository: repo })).rejects.toThrow(/COVERAGE/); }],
    ["strict schema fails before persistence", async () => { const bad = { ...output(), capabilities: [{ ...output().capabilities[0], unexpected: true }] } as any; await expect(runCapabilityDiscovery([doc], { kernelVersion: "v", schemaVersion: "1" }, { kernelResolver: resolver, provider: provider(bad), repository: new InMemoryCapabilityCoreRepository() })).rejects.toThrow(/SCHEMA/); }],
    ["no sources before provider", async () => { await expect(runCapabilityDiscovery([], { kernelVersion: "v", schemaVersion: "1" }, { kernelResolver: resolver, provider: { ...provider(), execute: async () => { throw new Error("called"); } }, repository: new InMemoryCapabilityCoreRepository() })).rejects.toThrow(/NO_SOURCES/); }],
    ["duplicate docId before provider", async () => { await expect(runCapabilityDiscovery([doc, doc], { kernelVersion: "v", schemaVersion: "1" }, { kernelResolver: resolver, provider: { ...provider(), execute: async () => { throw new Error("called"); } }, repository: new InMemoryCapabilityCoreRepository() })).rejects.toThrow(/DUPLICATE_DOC_ID/); }],
    ["no VerifiedCapability or final CAP ID", async () => { const r = await runCapabilityDiscovery([doc], { kernelVersion: "v", schemaVersion: "1" }, { kernelResolver: resolver, provider: provider(), repository: new InMemoryCapabilityCoreRepository() }); const serialized = JSON.stringify(r); expect(serialized).not.toContain("VerifiedCapability"); expect(serialized).not.toMatch(/CAP_[A-Z0-9]+/); expect((r as any).run.payload.candidates[0].candidateId).toMatch(/^CAND_/); }],
    ["provider abstract mock", async () => { const r = await runCapabilityDiscovery([doc], { kernelVersion: "v", schemaVersion: "1" }, { kernelResolver: resolver, provider: { ...provider(), providerName: "local" }, repository: new InMemoryCapabilityCoreRepository() }); expect((r as any).run.inference.provider).toBe("local"); }]
  ])("runtime: %s", async (_name, execute) => execute());
  it("secret marker is absent from returned, loaded, and reused runs", async () => { const repository = new InMemoryCapabilityCoreRepository(); const deps = { kernelResolver: resolver, provider: provider(), repository }; const completed = await runCapabilityDiscovery([doc], { kernelVersion: "v", schemaVersion: "1" }, deps); const loaded = await repository.getRunById((completed as any).run.runId); const reused = await runCapabilityDiscovery([doc], { kernelVersion: "v", schemaVersion: "1" }, { ...deps, provider: { ...provider(), execute: async () => { throw new Error("called"); } } }); expect(JSON.stringify(completed)).not.toContain(marker); expect(JSON.stringify(loaded)).not.toContain(marker); expect(JSON.stringify(reused)).not.toContain(marker); });
  it.each([["missing model", () => new GeminiCapabilityDiscoveryProvider({ model: "", apiKey: "KEY" })], ["missing API key", () => new GeminiCapabilityDiscoveryProvider({ model: "model", apiKey: "" }).execute({ systemPrompt: "K", userPrompt: "S" })]])("Gemini guard: %s", async (_name, action) => { await expect(Promise.resolve().then(action)).rejects.toThrow(/CAPABILITY_DISCOVERY_(MODEL_NOT_CONFIGURED|GEMINI_KEY_MISSING)/); });
  it("Gemini uses one fixed generation profile and one request", async () => { let calls = 0; let request: any; const client = { models: { generateContent: async (value: any) => { calls++; request = value; return { text: JSON.stringify(output()) }; } } }; await new GeminiCapabilityDiscoveryProvider({ model: "exact-model", apiKey: "FAKE_GEMINI_API_KEY", client }).execute({ systemPrompt: marker, userPrompt: "SOURCE" }); expect(calls).toBe(1); expect(request.model).toBe("exact-model"); expect(request.config).toMatchObject({ responseMimeType: "application/json", temperature: 0.1, maxOutputTokens: 32768 }); });
  it.each([["markdown fenced output", "```json\n{}\n```"], ["provider exception", "THROW"]])("Gemini rejects/contains failures without leakage: %s", async (_name, text) => { const client = { models: { generateContent: async () => { if (text === "THROW") throw new Error(`${marker} FAKE_GEMINI_API_KEY SOURCE`); return { text }; } } }; const provider = new GeminiCapabilityDiscoveryProvider({ model: "model", apiKey: "FAKE_GEMINI_API_KEY", client }); await expect(provider.execute({ systemPrompt: marker, userPrompt: "SOURCE" })).rejects.toThrow(/STRUCTURED_OUTPUT_INVALID|PROVIDER_FAILURE/); try { await provider.execute({ systemPrompt: marker, userPrompt: "SOURCE" }); } catch (error) { expect(String(error)).not.toContain(marker); expect(String(error)).not.toContain("FAKE_GEMINI_API_KEY"); expect(String(error)).not.toContain("SOURCE"); } });
  it("VERIFIED snapshots bypass the provider", async () => { const evidence: EvidenceClaim = { evidenceId: "EVD_TEST", sourceDocumentRef: "D", declaredLocation: "section", exactQuote: "Literal proof.", verification: { status: "VERIFIED" } }; const capability: VerifiedCapability = { capabilityId: "PCAP_TEST", canonicalName: "Candidate", scope: "ATOMIC", structuralDefinition: "D", primaryDomain: null, demonstratedCapabilityLevel: null, levelVerificationStatus: "UNVERIFIED", evidenceIds: [evidence.evidenceId], relationIds: [], provenance: { sourceCandidateIds: ["CAND_TEST"], sourceDocumentIds: ["D"] }, validation: { evidenceStatus: "PASSED", semanticDefinitionStatus: "NOT_RUN", convergenceStatus: "MANUAL_GOLD" } }; const repository = new InMemoryCapabilityCoreRepository(); const snapshot = createVerifiedCapabilitySnapshot({ sourceBundleHash: computeSourceBundleHash([doc]), kernelVersion: "v", prompt: { checksum: "C" }, inference: { provider: "mock", model: "model-1" }, schemaVersion: "1", candidateCount: 1, rejectedCandidateCount: 0, createdAt: "now", status: "VERIFIED" }, [capability], [evidence]); await repository.saveSnapshot(snapshot); const result = await runCapabilityDiscovery([doc], { kernelVersion: "v", schemaVersion: "1" }, { kernelResolver: resolver, provider: { ...provider(), execute: async () => { throw new Error("provider called"); } }, repository }); expect(result.kind).toBe("VERIFIED_SNAPSHOT_REUSED"); });
  it("in-memory run reads are deep-cloned and immutable", async () => { const repository = new InMemoryCapabilityCoreRepository(); const result = await runCapabilityDiscovery([doc], { kernelVersion: "v", schemaVersion: "1" }, { kernelResolver: resolver, provider: provider(), repository }); const run = (result as any).run; const loaded = await repository.getRunById(run.runId); loaded.status = "MUTATED"; expect((await repository.getRunById(run.runId))!.status).toBe("COMPLETED"); await expect(repository.saveRun(run)).resolves.toBeUndefined(); await expect(repository.saveRun({ ...run, status: "FAILED" })).rejects.toThrow("ERR_IMMUTABLE_RUN_CONFLICT"); });
});
