import { eq } from "drizzle-orm";
import type { PostgresJsDatabase } from "drizzle-orm/postgres-js";
import { assertTargetRoleProfileRevision, createBoundTargetRoleProfileRevisionPersister, sameTargetRoleProfileRevisionData, type BoundTargetRoleProfileRevisionPersister, type TargetRoleProfileOperandLookup, type TargetRoleProfileRevision, type TargetRoleProfileRevisionRepository } from "../../target/role";
import { targetRoleProfileRevisions } from "./postgres-schema";
const invalid = (): never => { throw new Error("ERR_TARGET_ROLE_PROFILE_REVISION_POSTGRES_RECORD_INVALID"); };
const valid = (value: unknown): value is string => typeof value === "string" && value.length > 0;
function row(value: { targetRoleProfileRevisionId: unknown; targetRoleEntityId: unknown; targetRoleOrganizationBindingRevisionId: unknown; previousRevisionId: unknown; payload: unknown }, requested?: string): TargetRoleProfileRevision { try { if (!valid(value.targetRoleProfileRevisionId) || !valid(value.targetRoleEntityId) || !valid(value.targetRoleOrganizationBindingRevisionId) || (value.previousRevisionId !== null && !valid(value.previousRevisionId)) || (requested !== undefined && value.targetRoleProfileRevisionId !== requested)) return invalid(); const revision = structuredClone(value.payload) as TargetRoleProfileRevision; assertTargetRoleProfileRevision(revision); if (revision.targetRoleProfileRevisionId !== value.targetRoleProfileRevisionId || revision.targetRoleEntityId !== value.targetRoleEntityId || revision.targetRoleOrganizationBindingRevisionId !== value.targetRoleOrganizationBindingRevisionId || revision.previousRevisionId !== value.previousRevisionId) return invalid(); return structuredClone(revision); } catch { return invalid(); } }
export class PostgresTargetRoleProfileRevisionRepository implements TargetRoleProfileRevisionRepository {
  constructor(private readonly database: PostgresJsDatabase, private readonly operands: TargetRoleProfileOperandLookup) {}
  async getRevisionById(id: string): Promise<TargetRoleProfileRevision | null> { const rows = await this.database.select().from(targetRoleProfileRevisions).where(eq(targetRoleProfileRevisions.targetRoleProfileRevisionId, id)).limit(1); return rows.length === 0 ? null : row(rows[0], id); }
  createTargetRoleProfileRevisionPersister(): BoundTargetRoleProfileRevisionPersister { return createBoundTargetRoleProfileRevisionPersister({ getRevisionById: this.getRevisionById.bind(this), getTargetRoleOrganizationBindingRevisionById: this.operands.getTargetRoleOrganizationBindingRevisionById.bind(this.operands), getTargetOrganizationRevisionById: this.operands.getTargetOrganizationRevisionById.bind(this.operands), writeRevision: this.#write.bind(this) }); }
  async #write(revision: TargetRoleProfileRevision): Promise<void> { const inserted = await this.database.insert(targetRoleProfileRevisions).values({ targetRoleProfileRevisionId: revision.targetRoleProfileRevisionId, targetRoleEntityId: revision.targetRoleEntityId, targetRoleOrganizationBindingRevisionId: revision.targetRoleOrganizationBindingRevisionId, previousRevisionId: revision.previousRevisionId, payload: structuredClone(revision) }).onConflictDoNothing().returning({ id: targetRoleProfileRevisions.targetRoleProfileRevisionId }); if (inserted.length === 1) return; let winner: TargetRoleProfileRevision | null; try { winner = await this.getRevisionById(revision.targetRoleProfileRevisionId); } catch (error) { if (error instanceof Error && error.message === "ERR_TARGET_ROLE_PROFILE_REVISION_POSTGRES_RECORD_INVALID") throw new Error("ERR_TARGET_ROLE_PROFILE_REVISION_PERSISTENCE_INVALID"); throw error; } if (winner === null) throw new Error("ERR_TARGET_ROLE_PROFILE_REVISION_PERSISTENCE_INVALID"); if (!sameTargetRoleProfileRevisionData(winner, revision)) throw new Error("ERR_TARGET_ROLE_PROFILE_REVISION_IMMUTABLE_CONFLICT"); }
}
