import { eq } from "drizzle-orm";
import type { PostgresJsDatabase } from "drizzle-orm/postgres-js";
import { assertCapabilityRequirementRelation, assertCapabilityRequirementRelationEvaluationResult, assertCapabilityRequirementRelationEvaluationRun, assertCapabilityRequirementRelationRawProviderOutputArtifact, sameCapabilityRequirementRelationData } from "../../relation/capability-requirement/contract";
import type { CapabilityRequirementRelation, CapabilityRequirementRelationEvaluationResult, CapabilityRequirementRelationEvaluationRun, CapabilityRequirementRelationRawProviderOutputArtifact } from "../../relation/capability-requirement/types";
import type { CapabilityRequirementRelationRepository } from "../../relation/capability-requirement/persistence";
import { capabilityRequirementRelationEvaluationResults, capabilityRequirementRelationEvaluationRuns, capabilityRequirementRelationRawProviderOutputs, capabilityRequirementRelations } from "./postgres-schema";

const fail = (code: string): never => { throw new Error(code); };
async function write<T>(insert: Promise<unknown[]>, read: () => Promise<T | null>, value: T): Promise<T> { const inserted = await insert; const winner = await read(); if (winner === null) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); if (!sameCapabilityRequirementRelationData(winner, value)) fail(inserted.length ? "ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID" : "ERR_CAPABILITY_REQUIREMENT_RELATION_IMMUTABLE_CONFLICT"); return structuredClone(winner!) as T; }

export class PostgresCapabilityRequirementRelationRepository implements CapabilityRequirementRelationRepository {
  constructor(private readonly database: PostgresJsDatabase) {}
  async getRawProviderOutputByRef(id: string) { const rows = await this.database.select().from(capabilityRequirementRelationRawProviderOutputs).where(eq(capabilityRequirementRelationRawProviderOutputs.rawProviderOutputRef, id)).limit(1); if (!rows.length) return null; const row = rows[0]; try { assertCapabilityRequirementRelationRawProviderOutputArtifact(row.payload); if (row.rawProviderOutputRef !== row.payload.rawProviderOutputRef || row.rawProviderOutputHash !== row.payload.rawProviderOutputHash) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); return structuredClone(row.payload); } catch { return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); } }
  async getRunById(id: string) { const rows = await this.database.select().from(capabilityRequirementRelationEvaluationRuns).where(eq(capabilityRequirementRelationEvaluationRuns.capabilityRequirementRelationEvaluationRunId, id)).limit(1); if (!rows.length) return null; const row = rows[0]; try { assertCapabilityRequirementRelationEvaluationRun(row.payload); if (row.capabilityRequirementRelationEvaluationRunId !== row.payload.capabilityRequirementRelationEvaluationRunId || row.verifiedCapabilitySnapshotId !== row.payload.candidate.verifiedCapabilitySnapshotId || row.targetRequirementRevisionId !== row.payload.targetRequirementRevisionId || row.rawProviderOutputRef !== row.payload.rawProviderOutputRef) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); return structuredClone(row.payload); } catch { return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); } }
  async getResultById(id: string) { const rows = await this.database.select().from(capabilityRequirementRelationEvaluationResults).where(eq(capabilityRequirementRelationEvaluationResults.capabilityRequirementRelationEvaluationResultId, id)).limit(1); if (!rows.length) return null; const row = rows[0]; try { assertCapabilityRequirementRelationEvaluationResult(row.payload); if (row.capabilityRequirementRelationEvaluationResultId !== row.payload.capabilityRequirementRelationEvaluationResultId || row.capabilityRequirementRelationEvaluationRunId !== row.payload.capabilityRequirementRelationEvaluationRunId || row.verifiedCapabilitySnapshotId !== row.payload.candidate.verifiedCapabilitySnapshotId || row.targetRequirementRevisionId !== row.payload.targetRequirementRevisionId) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); return structuredClone(row.payload); } catch { return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); } }
  async getRelationById(id: string) { const rows = await this.database.select().from(capabilityRequirementRelations).where(eq(capabilityRequirementRelations.capabilityRequirementRelationId, id)).limit(1); if (!rows.length) return null; const row = rows[0]; try { assertCapabilityRequirementRelation(row.payload); if (row.capabilityRequirementRelationId !== row.payload.capabilityRequirementRelationId || row.capabilityRequirementRelationEvaluationResultId !== row.payload.lineage.capabilityRequirementRelationEvaluationResultId || row.verifiedCapabilitySnapshotId !== row.payload.operands.candidate.verifiedCapabilitySnapshotId || row.targetRequirementRevisionId !== row.payload.operands.targetRequirementRevisionId) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); return structuredClone(row.payload); } catch { return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); } }
  async persistRawProviderOutput(value: CapabilityRequirementRelationRawProviderOutputArtifact) { assertCapabilityRequirementRelationRawProviderOutputArtifact(value); return write(this.database.insert(capabilityRequirementRelationRawProviderOutputs).values({ rawProviderOutputRef: value.rawProviderOutputRef, rawProviderOutputHash: value.rawProviderOutputHash, payload: structuredClone(value) }).onConflictDoNothing().returning(), () => this.getRawProviderOutputByRef(value.rawProviderOutputRef), value); }
  async persistRun(value: CapabilityRequirementRelationEvaluationRun) { assertCapabilityRequirementRelationEvaluationRun(value); if (value.rawProviderOutputRef !== null) { const raw = await this.getRawProviderOutputByRef(value.rawProviderOutputRef); if (raw === null || raw.rawProviderOutputHash !== value.rawProviderOutputHash) fail("ERR_CAPABILITY_REQUIREMENT_RELATION_RAW_OUTPUT_NOT_FOUND"); } return write(this.database.insert(capabilityRequirementRelationEvaluationRuns).values({ capabilityRequirementRelationEvaluationRunId: value.capabilityRequirementRelationEvaluationRunId, verifiedCapabilitySnapshotId: value.candidate.verifiedCapabilitySnapshotId, targetRequirementRevisionId: value.targetRequirementRevisionId, rawProviderOutputRef: value.rawProviderOutputRef, payload: structuredClone(value) }).onConflictDoNothing().returning(), () => this.getRunById(value.capabilityRequirementRelationEvaluationRunId), value); }
  async persistResult(value: CapabilityRequirementRelationEvaluationResult) { assertCapabilityRequirementRelationEvaluationResult(value); const run = await this.getRunById(value.capabilityRequirementRelationEvaluationRunId); if (run === null) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_RUN_NOT_FOUND"); if (run.targetRequirementRevisionId !== value.targetRequirementRevisionId || !sameCapabilityRequirementRelationData(run.candidate, value.candidate) || (value.resultState === "COMPLETED") !== (run.status === "COMPLETED")) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); return write(this.database.insert(capabilityRequirementRelationEvaluationResults).values({ capabilityRequirementRelationEvaluationResultId: value.capabilityRequirementRelationEvaluationResultId, capabilityRequirementRelationEvaluationRunId: value.capabilityRequirementRelationEvaluationRunId, verifiedCapabilitySnapshotId: value.candidate.verifiedCapabilitySnapshotId, targetRequirementRevisionId: value.targetRequirementRevisionId, payload: structuredClone(value) }).onConflictDoNothing().returning(), () => this.getResultById(value.capabilityRequirementRelationEvaluationResultId), value); }
  async persistRelation(value: CapabilityRequirementRelation) { assertCapabilityRequirementRelation(value); const result = await this.getResultById(value.lineage.capabilityRequirementRelationEvaluationResultId); if (result === null || result.resultState !== "COMPLETED" || result.evaluation === null) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_RESULT_NOT_FOUND"); const run = await this.getRunById(result.capabilityRequirementRelationEvaluationRunId); const policyKeys = ["relationProducerVersion", "requirementAdmissionPolicyVersion", "semanticPolicyVersion", "levelPolicyVersion", "scopePolicyVersion", "evidencePolicyVersion"] as const; if (run === null || run.status !== "COMPLETED" || result.targetRequirementRevisionId !== value.operands.targetRequirementRevisionId || !sameCapabilityRequirementRelationData(result.candidate, value.operands.candidate) || !sameCapabilityRequirementRelationData(result.evaluation, value.evaluation) || policyKeys.some(key => value.lineage[key] !== run.producer[key])) return fail("ERR_CAPABILITY_REQUIREMENT_RELATION_PERSISTENCE_INVALID"); return write(this.database.insert(capabilityRequirementRelations).values({ capabilityRequirementRelationId: value.capabilityRequirementRelationId, capabilityRequirementRelationEvaluationResultId: value.lineage.capabilityRequirementRelationEvaluationResultId, verifiedCapabilitySnapshotId: value.operands.candidate.verifiedCapabilitySnapshotId, targetRequirementRevisionId: value.operands.targetRequirementRevisionId, payload: structuredClone(value) }).onConflictDoNothing().returning(), () => this.getRelationById(value.capabilityRequirementRelationId), value); }
}
