import { createHash } from "node:crypto";
import { assertDecisionAuthorityGrantRevision, type DecisionAuthorityGrantRevision, type PermittedDecisionClass, type PermittedSubjectKind } from "../decision-authority";
import { assertCareerDecisionContextWitnesses, type CareerDecisionContextRevision, type DecisionSubjectReference } from "../decision-context";
import { assertRecommendationProposal, type RecommendationProposal } from "../recommendation-proposal";
import { HUMAN_DECISION_RECORD_SCHEMA_VERSION, type HumanDecisionDeclarationClass, type HumanDecisionDeclarationInput, type HumanDecisionRecord } from "./types";
const fail=(code:string):never=>{throw new Error(code)};
const invalid=():never=>fail("ERR_HUMAN_DECISION_INVALID");
const compare=(a:string,b:string)=>a<b?-1:a>b?1:0;
const text=(v:unknown):v is string=>typeof v==="string"&&v.trim().length>0&&v===v.trim();
const timestamp=(v:unknown):v is string=>text(v)&&Number.isFinite(new Date(v).getTime())&&new Date(v).toISOString()===v;
const rcp=/^RCP_[0-9A-F]{32}$/,dctx=/^DCTXREV_[0-9A-F]{32}$/,dar=/^DAR_[0-9A-F]{32}$/,dcr=/^DCR_[0-9A-F]{32}$/;
const classes=["ACCEPT_RECOMMENDATION","REJECT_RECOMMENDATION","DEFER_DECISION","REQUEST_FURTHER_EVIDENCE","REQUEST_TARGET_CLARIFICATION"] as const;
const evidenceCodes=new Set(["EVIDENCE_INSUFFICIENT","EVIDENCE_UNKNOWN"]);
const targetCodes=new Set(["ELIGIBILITY_UNKNOWN","REQUIREMENT_REVISION_BRANCH_UNRESOLVED","REQUIREMENT_RELATION_AGGREGATE_SET_UNRESOLVED"]);
const revisionKeys=["humanDecisionRecordId","careerDecisionContextRevisionId","decisionAuthorityGrantRevisionId","recommendationProposalId","declarantActorId","decisionSubjects","declarationClass","declaredAt","declarationEvidenceRefs","authorityScope","permittedDecisionClasses","permittedSubjectKinds","schemaVersion","createdAt"] as const;
const semanticKeys=revisionKeys.filter(key=>key!=="humanDecisionRecordId"&&key!=="createdAt");
const inputKeys=["careerDecisionContextRevisionId","declarantActorId","declarationClass","declaredAt","declarationEvidenceRefs","createdAt"] as const;
const subjectKeys=["recommendationProposalId","sourceEvolutionInputItemOrdinal"] as const;
function object(value:unknown,keys:readonly string[],code="ERR_HUMAN_DECISION_INVALID"):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))fail(code);const actual=Object.keys(value as Record<string,unknown>);if(actual.length!==keys.length||keys.some(key=>!Object.prototype.hasOwnProperty.call(value,key)))fail(code);return value as Record<string,unknown>}
function inventory<T extends string>(value:unknown,allowed:readonly T[],normal:boolean):T[]{if(!Array.isArray(value)||value.length===0)invalid();const source=value as unknown[];if(source.some(v=>typeof v!=="string"||!allowed.includes(v as T)))invalid();const got=[...source] as T[];if(new Set(got).size!==got.length)invalid();const sorted=[...got].sort(compare);if(!normal&&JSON.stringify(got)!==JSON.stringify(sorted))invalid();return sorted}
function subjects(value:unknown,normal:boolean):DecisionSubjectReference[]{if(!Array.isArray(value)||value.length===0)fail("ERR_HUMAN_DECISION_SUBJECT_NOT_ADMISSIBLE");const source=value as unknown[];const got=source.map(item=>{const subject=object(item,subjectKeys,"ERR_HUMAN_DECISION_SUBJECT_NOT_ADMISSIBLE");if(!rcp.test(subject.recommendationProposalId as string)||!Number.isSafeInteger(subject.sourceEvolutionInputItemOrdinal)||(subject.sourceEvolutionInputItemOrdinal as number)<0)fail("ERR_HUMAN_DECISION_SUBJECT_NOT_ADMISSIBLE");return {recommendationProposalId:subject.recommendationProposalId as string,sourceEvolutionInputItemOrdinal:subject.sourceEvolutionInputItemOrdinal as number}});const key=(s:DecisionSubjectReference)=>`${s.recommendationProposalId}:${String(s.sourceEvolutionInputItemOrdinal).padStart(12,"0")}`;if(new Set(got.map(key)).size!==got.length)fail("ERR_HUMAN_DECISION_SUBJECT_NOT_ADMISSIBLE");const sorted=[...got].sort((a,b)=>compare(key(a),key(b)));if(!normal&&JSON.stringify(got)!==JSON.stringify(sorted))fail("ERR_HUMAN_DECISION_SUBJECT_NOT_ADMISSIBLE");return sorted}
function evidence(value:unknown,normal:boolean):string[]{if(!Array.isArray(value)||value.length===0)invalid();const source=value as unknown[];if(source.some(v=>!text(v)))invalid();const got=[...source] as string[];if(new Set(got).size!==got.length)invalid();const sorted=[...got].sort(compare);if(!normal&&JSON.stringify(got)!==JSON.stringify(sorted))invalid();return sorted}
function semantic(value:Record<string,unknown>,normal:boolean){if(!dctx.test(value.careerDecisionContextRevisionId as string)||!dar.test(value.decisionAuthorityGrantRevisionId as string)||!rcp.test(value.recommendationProposalId as string)||!text(value.declarantActorId)||!classes.includes(value.declarationClass as HumanDecisionDeclarationClass)||!timestamp(value.declaredAt)||value.authorityScope!=="CAREER_RECOMMENDATION_DECISION"||value.schemaVersion!==HUMAN_DECISION_RECORD_SCHEMA_VERSION)invalid();return {careerDecisionContextRevisionId:value.careerDecisionContextRevisionId as string,decisionAuthorityGrantRevisionId:value.decisionAuthorityGrantRevisionId as string,recommendationProposalId:value.recommendationProposalId as string,declarantActorId:value.declarantActorId as string,decisionSubjects:subjects(value.decisionSubjects,normal),declarationClass:value.declarationClass as HumanDecisionDeclarationClass,declaredAt:value.declaredAt as string,declarationEvidenceRefs:evidence(value.declarationEvidenceRefs,normal),authorityScope:"CAREER_RECOMMENDATION_DECISION" as const,permittedDecisionClasses:inventory(value.permittedDecisionClasses,classes,normal) as PermittedDecisionClass[],permittedSubjectKinds:inventory(value.permittedSubjectKinds,["RCP_ITEM"] as const,normal) as PermittedSubjectKind[],schemaVersion:HUMAN_DECISION_RECORD_SCHEMA_VERSION}}
export function stableHumanDecision(value:unknown):string{return JSON.stringify(value,(_k,item)=>item&&typeof item==="object"&&!Array.isArray(item)?Object.fromEntries(Object.keys(item as Record<string,unknown>).sort(compare).map(k=>[k,(item as Record<string,unknown>)[k]])):item)}
export function deriveHumanDecisionRecordId(value:Omit<HumanDecisionRecord,"humanDecisionRecordId"|"createdAt">):string{const v=semantic(object(value,semanticKeys),false);return `DCR_${createHash("sha256").update(stableHumanDecision([HUMAN_DECISION_RECORD_SCHEMA_VERSION,v.careerDecisionContextRevisionId,v.decisionAuthorityGrantRevisionId,v.recommendationProposalId,v.declarantActorId,v.decisionSubjects,v.declarationClass,v.declaredAt,v.declarationEvidenceRefs,v.authorityScope,v.permittedDecisionClasses,v.permittedSubjectKinds,v.schemaVersion]),"utf8").digest("hex").slice(0,32).toUpperCase()}`}
export function assertHumanDecisionRecord(value:unknown):asserts value is HumanDecisionRecord{const v=object(value,revisionKeys);if(!dcr.test(v.humanDecisionRecordId as string)||!timestamp(v.createdAt))invalid();const canonical=semantic(v,false);if(v.humanDecisionRecordId!==deriveHumanDecisionRecordId(canonical))invalid()}
function sourceItems(context:CareerDecisionContextRevision,proposal:RecommendationProposal){return context.decisionSubjects.map(subject=>proposal.items.find(item=>item.sourceEvolutionInputItemOrdinal===subject.sourceEvolutionInputItemOrdinal)??fail("ERR_HUMAN_DECISION_SUBJECT_NOT_ADMISSIBLE"))}
function assertAdmissibility(kind:HumanDecisionDeclarationClass,items:ReturnType<typeof sourceItems>){if((kind==="ACCEPT_RECOMMENDATION"||kind==="REJECT_RECOMMENDATION")&&items.some(item=>item.recommendationDisposition!=="PROPOSED"))fail("ERR_HUMAN_DECISION_SUBJECT_NOT_ADMISSIBLE");if(kind==="REQUEST_FURTHER_EVIDENCE"&&items.some(item=>!evidenceCodes.has(item.tensionClassificationCode)))fail("ERR_HUMAN_DECISION_SUBJECT_NOT_ADMISSIBLE");if(kind==="REQUEST_TARGET_CLARIFICATION"&&items.some(item=>!targetCodes.has(item.tensionClassificationCode)))fail("ERR_HUMAN_DECISION_SUBJECT_NOT_ADMISSIBLE")}
function assertApplicable(authority:DecisionAuthorityGrantRevision,at:string){if(at<authority.effectiveFrom||(authority.effectiveUntil!==null&&at>=authority.effectiveUntil))fail("ERR_HUMAN_DECISION_AUTHORITY_NOT_APPLICABLE")}
/** Validates durable declaration lineage; it does not recreate a human declaration. */
export function assertHumanDecisionWitnesses(record:HumanDecisionRecord,context:CareerDecisionContextRevision,authority:DecisionAuthorityGrantRevision,proposal:RecommendationProposal):void{assertHumanDecisionRecord(record);try{assertDecisionAuthorityGrantRevision(authority)}catch{fail("ERR_HUMAN_DECISION_AUTHORITY_GRANT_INVALID")}try{assertRecommendationProposal(proposal)}catch{fail("ERR_HUMAN_DECISION_RECOMMENDATION_PROPOSAL_INVALID")}try{assertCareerDecisionContextWitnesses(context,authority,proposal)}catch{fail("ERR_HUMAN_DECISION_CONTEXT_INVALID")}if(record.careerDecisionContextRevisionId!==context.careerDecisionContextRevisionId||record.decisionAuthorityGrantRevisionId!==authority.decisionAuthorityGrantRevisionId||record.recommendationProposalId!==proposal.recommendationProposalId)invalid();if(record.declarantActorId!==authority.authorizedActorId)fail("ERR_HUMAN_DECISION_DECLARANT_MISMATCH");if(!authority.permittedDecisionClasses.includes(record.declarationClass))fail("ERR_HUMAN_DECISION_CLASS_NOT_PERMITTED");if(!authority.permittedSubjectKinds.includes("RCP_ITEM"))fail("ERR_HUMAN_DECISION_SUBJECT_KIND_NOT_PERMITTED");if(JSON.stringify(record.decisionSubjects)!==JSON.stringify(context.decisionSubjects)||record.authorityScope!==authority.authorityScope||JSON.stringify(record.permittedDecisionClasses)!==JSON.stringify(authority.permittedDecisionClasses)||JSON.stringify(record.permittedSubjectKinds)!==JSON.stringify(authority.permittedSubjectKinds))invalid();assertApplicable(authority,record.declaredAt);assertAdmissibility(record.declarationClass,sourceItems(context,proposal))}
/** Construction copies every witness from exact historical context, grant, and proposal. */
export function createHumanDecisionRecord(context:CareerDecisionContextRevision,authority:DecisionAuthorityGrantRevision,proposal:RecommendationProposal,input:HumanDecisionDeclarationInput):HumanDecisionRecord{const captured=object(input,inputKeys);if(!timestamp(captured.declaredAt)||!timestamp(captured.createdAt)||!text(captured.declarantActorId))invalid();if(captured.careerDecisionContextRevisionId!==context.careerDecisionContextRevisionId)fail("ERR_HUMAN_DECISION_CONTEXT_INVALID");const canonical=semantic({careerDecisionContextRevisionId:context.careerDecisionContextRevisionId,decisionAuthorityGrantRevisionId:authority.decisionAuthorityGrantRevisionId,recommendationProposalId:proposal.recommendationProposalId,declarantActorId:captured.declarantActorId,decisionSubjects:context.decisionSubjects,declarationClass:captured.declarationClass,declaredAt:captured.declaredAt,declarationEvidenceRefs:evidence(captured.declarationEvidenceRefs,true),authorityScope:authority.authorityScope,permittedDecisionClasses:authority.permittedDecisionClasses,permittedSubjectKinds:authority.permittedSubjectKinds,schemaVersion:HUMAN_DECISION_RECORD_SCHEMA_VERSION},true);const record:HumanDecisionRecord={humanDecisionRecordId:deriveHumanDecisionRecordId(canonical),...canonical,createdAt:captured.createdAt as string};assertHumanDecisionWitnesses(record,context,authority,proposal);return structuredClone(record)}
export function sameHumanDecision(left:unknown,right:unknown):boolean{try{assertHumanDecisionRecord(left);assertHumanDecisionRecord(right);return stableHumanDecision(left)===stableHumanDecision(right)}catch{return false}}
