import type { DecisionAuthorityGrantRevisionRepository } from "../decision-authority";
import type { CareerDecisionContextRevisionRepository } from "../decision-context";
import type { RecommendationProposalRepository } from "../recommendation-proposal";
import { createHumanDecisionRecord, sameHumanDecision } from "./contract";
import type { HumanDecisionRecordRepository } from "./persistence";
import type { HumanDecisionDeclarationInput } from "./types";
const fail=(code:string):never=>{throw new Error(code)};
export interface HumanDecisionProducerDependencies{contexts:CareerDecisionContextRevisionRepository;authorities:DecisionAuthorityGrantRevisionRepository;proposals:RecommendationProposalRepository;records:HumanDecisionRecordRepository;}
/** Production receives a declaration and context ID only; all authority and proposal lineage is exact-read from the context. */
export async function produceAndPersistHumanDecisionRecord(input:HumanDecisionDeclarationInput,dependencies:HumanDecisionProducerDependencies){let context;try{context=await dependencies.contexts.getCareerDecisionContextRevisionById(input.careerDecisionContextRevisionId)}catch{fail("ERR_HUMAN_DECISION_CONTEXT_INVALID")}const exactContext=context??fail("ERR_HUMAN_DECISION_CONTEXT_NOT_FOUND");let authority;try{authority=await dependencies.authorities.getDecisionAuthorityGrantRevisionById(exactContext.decisionAuthorityGrantRevisionId)}catch{fail("ERR_HUMAN_DECISION_AUTHORITY_GRANT_INVALID")}const exactAuthority=authority??fail("ERR_HUMAN_DECISION_AUTHORITY_GRANT_NOT_FOUND");let proposal;try{proposal=await dependencies.proposals.getRecommendationProposalById(exactContext.recommendationProposalId)}catch{fail("ERR_HUMAN_DECISION_RECOMMENDATION_PROPOSAL_INVALID")}const exactProposal=proposal??fail("ERR_HUMAN_DECISION_RECOMMENDATION_PROPOSAL_NOT_FOUND");const value=createHumanDecisionRecord(exactContext,exactAuthority,exactProposal,input);try{const persisted=await dependencies.records.persistHumanDecisionRecord(value);if(!sameHumanDecision(persisted,value))fail("ERR_HUMAN_DECISION_PERSISTENCE_FAILED");return persisted}catch(error){if(error instanceof Error&&error.message==="ERR_HUMAN_DECISION_IMMUTABLE_CONFLICT")throw error;return fail("ERR_HUMAN_DECISION_PERSISTENCE_FAILED")}}
