import { GoogleGenAI } from "@google/genai";
import { InferenceProvider, PromptBuilderOutput } from "../adapter";

export const DEFAULT_GEMINI_MODEL_CASCADE = [
  "gemini-2.5-flash",
  "gemini-2.0-flash",
  "gemini-1.5-pro",
  "gemini-1.5-flash"
];

export interface AttemptedModelTelemetry {
  model: string;
  status: "SUCCESS" | "RATE_LIMITED" | "FAILED";
  latencyMs: number;
  error?: string;
}

export interface InferenceTelemetry {
  modelsAttempted: AttemptedModelTelemetry[];
  activeModel: string;
  fallbackTriggered: boolean;
  totalLatencyMs: number;
}

export interface GeminiProviderOptions {
  apiKey?: string;
  model?: string;
  modelCascade?: string[];
}

/**
 * Server-Side Google Gemini Inference Provider ("Dumb Consumer" boundary).
 * Implements canonical InferenceProvider contract without leaking SDK or API keys to client.
 * Features an autonomous Multi-Model Failover Cascade that switches models on 503/429 overload.
 */
export class GeminiProvider implements InferenceProvider {
  private apiKey?: string;
  private modelCascade: string[];
  public lastTelemetry?: InferenceTelemetry;

  constructor(options?: GeminiProviderOptions) {
    this.apiKey = options?.apiKey || process.env.GEMINI_API_KEY;
    if (options?.modelCascade && options.modelCascade.length > 0) {
      this.modelCascade = options.modelCascade;
    } else if (options?.model || process.env.GEMINI_MODEL) {
      const primary = options?.model || process.env.GEMINI_MODEL!;
      this.modelCascade = [
        primary,
        ...DEFAULT_GEMINI_MODEL_CASCADE.filter((m) => m !== primary)
      ];
    } else {
      this.modelCascade = [...DEFAULT_GEMINI_MODEL_CASCADE];
    }
  }

  /**
   * Executes the prompt bundle against Google Gemini API via @google/genai SDK.
   * Cycles through modelCascade on 503/429 or transient service errors.
   */
  async execute(prompt: PromptBuilderOutput): Promise<string> {
    const resolvedKey = this.apiKey || process.env.GEMINI_API_KEY;
    if (!resolvedKey) {
      throw new Error("ERR_PROVIDER_FAILURE: Missing GEMINI_API_KEY environment variable or constructor option.");
    }

    const startTime = Date.now();
    const modelsAttempted: AttemptedModelTelemetry[] = [];
    let lastError: Error | null = null;

    for (let i = 0; i < this.modelCascade.length; i++) {
      const currentModel = this.modelCascade[i];
      const attemptStart = Date.now();

      try {
        const ai = new GoogleGenAI({ apiKey: resolvedKey });
        const response = await ai.models.generateContent({
          model: currentModel,
          contents: prompt.userPrompt,
          config: {
            systemInstruction: prompt.systemPrompt,
            responseMimeType: "application/json",
            temperature: 0.1,
            maxOutputTokens: process.env.GEMINI_MAX_OUTPUT_TOKENS
              ? parseInt(process.env.GEMINI_MAX_OUTPUT_TOKENS, 10)
              : 32768
          }
        });

        const rawText = typeof (response as any).text === "function" ? await (response as any).text() : response.text;
        if (!rawText || typeof rawText !== "string") {
          throw new Error("Empty or non-string response generated by Gemini API.");
        }

        const latencyMs = Date.now() - attemptStart;
        modelsAttempted.push({
          model: currentModel,
          status: "SUCCESS",
          latencyMs
        });

        this.lastTelemetry = {
          modelsAttempted,
          activeModel: currentModel,
          fallbackTriggered: i > 0,
          totalLatencyMs: Date.now() - startTime
        };

        return rawText.trim();
      } catch (err: any) {
        const latencyMs = Date.now() - attemptStart;
        const errorMsg = err?.message || String(err);
        const isRateLimitOrOverload =
          errorMsg.includes("503") ||
          errorMsg.includes("429") ||
          errorMsg.includes("high demand") ||
          errorMsg.includes("UNAVAILABLE") ||
          errorMsg.includes("RESOURCE_EXHAUSTED");

        modelsAttempted.push({
          model: currentModel,
          status: isRateLimitOrOverload ? "RATE_LIMITED" : "FAILED",
          latencyMs,
          error: errorMsg
        });

        lastError = err;

        // If this is rate limit / overload and we have more models in cascade, continue to next model
        if (isRateLimitOrOverload && i < this.modelCascade.length - 1) {
          continue;
        }

        // If it's not a transient rate limit or we exhausted the cascade, stop
        if (!isRateLimitOrOverload) {
          break;
        }
      }
    }

    this.lastTelemetry = {
      modelsAttempted,
      activeModel: "NONE",
      fallbackTriggered: modelsAttempted.length > 1,
      totalLatencyMs: Date.now() - startTime
    };

    const finalErrorMsg = lastError?.message || String(lastError);
    if (finalErrorMsg.startsWith("ERR_PROVIDER_FAILURE:")) {
      throw lastError;
    }
    throw new Error(`ERR_PROVIDER_FAILURE: Google Gemini API execution failed across model cascade. Details: ${finalErrorMsg}`);
  }
}
