import { GoogleGenAI } from "@google/genai";
import { InferenceProvider, PromptBuilderOutput } from "../adapter";

export interface GeminiProviderOptions {
  apiKey?: string;
  model?: string;
}

/**
 * Server-Side Google Gemini Inference Provider ("Dumb Consumer" boundary).
 * Implements canonical InferenceProvider contract without leaking SDK or API keys to client.
 * Strictly enforces JSON structured output mode and encapsulates network/API errors.
 */
export class GeminiProvider implements InferenceProvider {
  private apiKey?: string;
  private model: string;

  constructor(options?: GeminiProviderOptions) {
    this.apiKey = options?.apiKey || process.env.GEMINI_API_KEY;
    this.model = options?.model || process.env.GEMINI_MODEL || "gemini-2.0-flash";
  }

  /**
   * Executes the prompt bundle against Google Gemini API via @google/genai SDK.
   * Returns unparsed raw JSON string output.
   */
  async execute(prompt: PromptBuilderOutput): Promise<string> {
    // Dynamically check key at execution time to allow test setup after constructor instantiation
    const resolvedKey = this.apiKey || process.env.GEMINI_API_KEY;
    if (!resolvedKey) {
      throw new Error("ERR_PROVIDER_FAILURE: Missing GEMINI_API_KEY environment variable or constructor option.");
    }

    try {
      const ai = new GoogleGenAI({ apiKey: resolvedKey });

      const response = await ai.models.generateContent({
        model: this.model,
        contents: prompt.userPrompt,
        config: {
          systemInstruction: prompt.systemPrompt,
          responseMimeType: "application/json",
          temperature: 0.1
        }
      });

      const rawText = typeof response.text === "function" ? await response.text() : response.text;
      if (!rawText || typeof rawText !== "string") {
        throw new Error("Empty or non-string response generated by Gemini API.");
      }

      return rawText.trim();
    } catch (err: any) {
      const errorMsg = err.message || String(err);
      if (errorMsg.startsWith("ERR_PROVIDER_FAILURE:")) {
        throw err;
      }
      throw new Error(`ERR_PROVIDER_FAILURE: Google Gemini API execution failed. Details: ${errorMsg}`);
    }
  }
}
