import { GoogleGenAI } from "@google/genai";
import { InferenceProvider, PromptBuilderOutput } from "../adapter";
import { getGeminiCareerResponseJsonSchema } from "../schema-projector";

export const DEFAULT_GEMINI_MODEL_CASCADE = [
  "gemini-2.0-flash",
  "gemini-2.5-flash",
  "gemini-1.5-pro",
  "gemini-1.5-flash"
];

export interface AttemptedModelTelemetry {
  model: string;
  status: "SUCCESS" | "RATE_LIMITED" | "FAILED";
  latencyMs: number;
  error?: string;
}

export interface InferenceTelemetry {
  modelsAttempted: AttemptedModelTelemetry[];
  activeModel: string;
  fallbackTriggered: boolean;
  totalLatencyMs: number;
  finishReason?: string;
  outputTokens?: number;
  inputTokens?: number;
  continuations?: number;
  complete?: boolean;
}

export interface GeminiProviderOptions {
  apiKey?: string;
  model?: string;
  modelCascade?: string[];
}

/**
 * Server-Side Google Gemini Inference Provider ("Dumb Consumer" boundary).
 * Implements canonical InferenceProvider contract without leaking SDK or API keys to client.
 * Features an autonomous Multi-Model Failover Cascade and auto-continuation for MAX_TOKENS.
 */
export class GeminiProvider implements InferenceProvider {
  private apiKey?: string;
  private modelCascade: string[];
  public lastTelemetry?: InferenceTelemetry;

  constructor(options?: GeminiProviderOptions) {
    this.apiKey = options?.apiKey || process.env.GEMINI_API_KEY;
    if (options?.modelCascade && options.modelCascade.length > 0) {
      this.modelCascade = options.modelCascade;
    } else if (options?.model || process.env.GEMINI_MODEL) {
      const primary = options?.model || process.env.GEMINI_MODEL!;
      this.modelCascade = [
        primary,
        ...DEFAULT_GEMINI_MODEL_CASCADE.filter((m) => m !== primary)
      ];
    } else {
      this.modelCascade = [...DEFAULT_GEMINI_MODEL_CASCADE];
    }
  }

  /**
   * Executes the prompt bundle against Google Gemini API via @google/genai SDK.
   * Cycles through modelCascade on 503/429 or transient service errors.
   * Automatically continues generation if finishReason === "MAX_TOKENS".
   */
  async execute(prompt: PromptBuilderOutput): Promise<string> {
    const resolvedKey = this.apiKey || process.env.GEMINI_API_KEY;
    if (!resolvedKey) {
      throw new Error("ERR_PROVIDER_FAILURE: Missing GEMINI_API_KEY environment variable or constructor option.");
    }

    const startTime = Date.now();
    const modelsAttempted: AttemptedModelTelemetry[] = [];
    let lastError: Error | null = null;

    for (let i = 0; i < this.modelCascade.length; i++) {
      const currentModel = this.modelCascade[i];
      const attemptStart = Date.now();

      try {
        const ai = new GoogleGenAI({ apiKey: resolvedKey });
        
        const MAX_CONTINUATIONS = process.env.GEMINI_MAX_CONTINUATIONS
          ? parseInt(process.env.GEMINI_MAX_CONTINUATIONS, 10)
          : 8;
        const chunks: string[] = [];
        let finishReason = "STOP";
        let inputTokens = 0;
        let outputTokens = 0;
        let continuations = 0;

        let contents: any = prompt.userPrompt;

        for (let step = 0; step <= MAX_CONTINUATIONS; step++) {
          const response = await ai.models.generateContent({
            model: currentModel,
            contents,
            config: {
              systemInstruction: prompt.systemPrompt,
              responseMimeType: "application/json",
              ...(step === 0 ? { responseJsonSchema: getGeminiCareerResponseJsonSchema() } : {}),
              temperature: 0.1,
              maxOutputTokens: process.env.GEMINI_MAX_OUTPUT_TOKENS
                ? parseInt(process.env.GEMINI_MAX_OUTPUT_TOKENS, 10)
                : 65536
            }
          });

          const candidate = (response as any).candidates?.[0];
          finishReason = candidate?.finishReason || "STOP";
          
          const usage = (response as any).usageMetadata;
          if (usage) {
            inputTokens += usage.promptTokenCount || 0;
            outputTokens += usage.candidatesTokenCount || usage.outputTokenCount || 0;
          }

          const rawText = typeof (response as any).text === "function" ? await (response as any).text() : response.text;
          if (!rawText || typeof rawText !== "string") {
            if (chunks.length > 0) break;
            throw new Error("Empty or non-string response generated by Gemini API.");
          }

          chunks.push(rawText);

          if (finishReason !== "MAX_TOKENS") {
            break;
          }

          continuations++;
          contents = [
            { role: "user", parts: [{ text: prompt.userPrompt }] },
            { role: "model", parts: [{ text: chunks.join("\n") }] },
            { role: "user", parts: [{ text: "Continue the JSON output exactly where it stopped. Do not repeat completed keys. Begin with the next missing property or section." }] }
          ];
        }

        const fullRawText = chunks.join("\n").trim();
        const latencyMs = Date.now() - attemptStart;

        modelsAttempted.push({
          model: currentModel,
          status: "SUCCESS",
          latencyMs
        });

        this.lastTelemetry = {
          modelsAttempted,
          activeModel: currentModel,
          fallbackTriggered: i > 0,
          totalLatencyMs: Date.now() - startTime,
          finishReason,
          outputTokens,
          inputTokens,
          continuations,
          complete: finishReason !== "MAX_TOKENS"
        };

        return fullRawText;
      } catch (err: any) {
        const latencyMs = Date.now() - attemptStart;
        const errorMsg = err?.message || String(err);
        const isRateLimitOrOverload =
          errorMsg.includes("503") ||
          errorMsg.includes("429") ||
          errorMsg.includes("high demand") ||
          errorMsg.includes("UNAVAILABLE") ||
          errorMsg.includes("RESOURCE_EXHAUSTED");

        modelsAttempted.push({
          model: currentModel,
          status: isRateLimitOrOverload ? "RATE_LIMITED" : "FAILED",
          latencyMs,
          error: errorMsg
        });

        lastError = err;

        if (isRateLimitOrOverload && i < this.modelCascade.length - 1) {
          continue;
        }

        if (!isRateLimitOrOverload) {
          break;
        }
      }
    }

    this.lastTelemetry = {
      modelsAttempted,
      activeModel: "NONE",
      fallbackTriggered: modelsAttempted.length > 1,
      totalLatencyMs: Date.now() - startTime,
      complete: false
    };

    const finalErrorMsg = lastError?.message || String(lastError);
    if (finalErrorMsg.startsWith("ERR_PROVIDER_FAILURE:")) {
      throw lastError;
    }
    throw new Error(`ERR_PROVIDER_FAILURE: Gemini Inference execution failed: ${finalErrorMsg}`);
  }
}
