import { randomBytes } from "node:crypto";
import { getTableConfig } from "drizzle-orm/pg-core";
import postgres, { type Sql } from "postgres";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { targetRequirementEntityAdmissions, targetRequirementRawProviderOutputs, targetRequirementReconstructionBatchRuns, targetRequirementReconstructionResults } from "../../../../lib/career/target-adapters/role-requirement-artifact-persistence";

const url = process.env.DATABASE_URL || "postgresql://postgres:postgres@localhost:5432/condyn"; const schema = `target_requirement_artifact_t5_${randomBytes(8).toString("hex")}`; let admin: Sql; const clients = new Set<Sql>(); const configs = [getTableConfig(targetRequirementRawProviderOutputs), getTableConfig(targetRequirementReconstructionBatchRuns), getTableConfig(targetRequirementReconstructionResults), getTableConfig(targetRequirementEntityAdmissions)]; const q = (x: string) => `"${x}"`; const table = (config: typeof configs[number]) => `CREATE TABLE ${q(schema)}.${q(config.name)} (${[...config.columns.map(c => `${q(c.name)} ${c.getSQLType()}${c.notNull ? " NOT NULL" : ""}${c.primary ? " PRIMARY KEY" : ""}`), ...config.foreignKeys.map(fk => { const r = fk.reference(); return `FOREIGN KEY (${r.columns.map(c => q(c.name)).join(",")}) REFERENCES ${q(schema)}.${q(getTableConfig(r.foreignTable).name)} (${r.foreignColumns.map(c => q(c.name)).join(",")}) ON DELETE ${(fk.onDelete ?? "no action").toUpperCase()}`; })].join(",")})`; const client = async () => { const sql = postgres(url, { max: 1, onnotice: () => undefined }); clients.add(sql); await sql.unsafe(`SET search_path TO "${schema}"`); return sql; };
beforeAll(async () => { admin = postgres(url, { max: 1, onnotice: () => undefined }); await admin.unsafe(`CREATE SCHEMA "${schema}"`); await admin.unsafe(`CREATE TABLE "${schema}"."target_role_profile_revisions" ("target_role_profile_revision_id" text PRIMARY KEY)`); for (const config of configs) await admin.unsafe(table(config)); }); afterAll(async () => { await Promise.all([...clients].map(sql => sql.end({ timeout: 5 }))); if (admin) { await admin.unsafe(`DROP SCHEMA "${schema}" CASCADE`); await admin.end({ timeout: 5 }); } });
describe("PostgreSQL Target Requirement Artifact T5", () => {
  it("owns only exact raw-batch-result-admission lineage foreign keys", () => { expect(getTableConfig(targetRequirementReconstructionBatchRuns).foreignKeys).toHaveLength(1); expect(getTableConfig(targetRequirementReconstructionResults).foreignKeys).toHaveLength(2); expect(getTableConfig(targetRequirementEntityAdmissions).foreignKeys).toHaveLength(1); });
  it("enforces exact batch/result physical lineage", async () => { const sql = await client(); await expect(sql.unsafe(`INSERT INTO target_requirement_reconstruction_results VALUES ('TRQRES_X','TRQRUN_MISSING','TRPREV_MISSING','{}'::jsonb)`)).rejects.toMatchObject({ code: "23503" }); await expect(sql.unsafe(`INSERT INTO target_requirement_entity_admissions VALUES ('TRQADM_X','TRQRES_MISSING','{}'::jsonb)`)).rejects.toMatchObject({ code: "23503" }); await sql.end({ timeout: 5 }); clients.delete(sql); });
});
