import type { CapabilityRequirementRelation, CapabilityRequirementRelationEvaluationResult } from "../capability-requirement";
import type { TargetRequirementRevision } from "../../target/role/requirement";

export type DirectRelationAdmission = "DIRECT_CAPABILITY_REQUIREMENT" | "TARGET_REQUIREMENT_INELIGIBLE" | "TARGET_REQUIREMENT_ELIGIBILITY_UNKNOWN" | "TARGET_REQUIREMENT_TYPE_NOT_DIRECT_CAPABILITY";
export type PairDisposition = "MATERIALIZED_RELATION" | "EVALUATION_FAILED" | "NOT_EVALUATED";
export interface T6BProtocol { relationProducerVersion: string; requirementAdmissionPolicyVersion: string; semanticPolicyVersion: string; levelPolicyVersion: string; scopePolicyVersion: string; evidencePolicyVersion: string; }
export interface TargetRoleRequirementGroup { targetRequirementEntityId: string; targetRequirementRevisionIds: string[]; revisionDisposition: "SINGLE_REVISION" | "MULTIPLE_REVISIONS_UNRESOLVED"; directRelationAdmission: DirectRelationAdmission | null; necessityStates: Array<{ targetRequirementRevisionId: string; necessityState: "REQUIRED" | "PREFERRED" | "OPTIONAL" | "CONDITIONAL" | "UNKNOWN" }>; }
/** Enumeration completeness is never Requirement satisfaction or a role conclusion. */
export interface TargetRoleRequirementInventory { targetRoleRequirementInventoryId: string; targetRoleProfileRevisionId: string; requirementGroups: TargetRoleRequirementGroup[]; inventoryState: "COMPLETE" | "PARTIAL"; failureReasons: string[]; lineage: { requirementInventoryPolicyVersion: string }; schemaVersion: "TARGET_ROLE_REQUIREMENT_INVENTORY_V1"; createdAt: string; }
export interface RequirementRelationPairDisposition { candidateCapabilityOperandId: string; disposition: PairDisposition; capabilityRequirementRelationId: string | null; capabilityRequirementRelationEvaluationResultId: string | null; }
export type DimensionInventory<T extends string> = Record<T, { count: number; capabilityRequirementRelationIds: string[] }>;
export interface RequirementRelationAggregate { requirementRelationAggregateId: string; targetRoleRequirementInventoryId: string; verifiedCapabilitySnapshotId: string; targetRequirementEntityId: string; targetRequirementRevisionId: string; candidateCapabilityOperandIds: string[]; pairDispositions: RequirementRelationPairDisposition[]; semanticRelationInventory: DimensionInventory<CapabilityRequirementRelation["evaluation"]["semanticRelation"]>; levelRelationInventory: DimensionInventory<CapabilityRequirementRelation["evaluation"]["levelRelation"]>; evidenceSufficiencyInventory: DimensionInventory<CapabilityRequirementRelation["evaluation"]["evidenceSufficiency"]>; scopeRelationInventory: DimensionInventory<CapabilityRequirementRelation["evaluation"]["scopeRelation"]>; composition: { state: "COMPOSITION_NOT_EVALUATED" }; lineage: { t6bProtocol: T6BProtocol; pairInventoryPolicyVersion: string; compositionPolicyVersion: string }; proposalState: "PROPOSAL_ONLY"; authorityState: "NONE"; schemaVersion: "REQUIREMENT_RELATION_AGGREGATE_V1"; createdAt: string; }
export interface RequirementInventoryDependencies { listTargetRequirementRevisionsByTargetRoleProfileRevisionId(id: string): Promise<TargetRequirementRevision[]>; }
export interface T6BPairRepository { getRelationById(id: string): Promise<CapabilityRequirementRelation | null>; getResultById(id: string): Promise<CapabilityRequirementRelationEvaluationResult | null>; getRunById(id: string): Promise<{ candidate: { candidateCapabilityOperandId: string; verifiedCapabilitySnapshotId: string }; targetRequirementRevisionId: string; producer: T6BProtocol; status: string } | null>; discoverPairTerminal(input:{candidateCapabilityOperandId:string;targetRequirementRevisionId:string;protocol:T6BProtocol}):Promise<{disposition:"MATERIALIZED_RELATION";relation:CapabilityRequirementRelation}|{disposition:"EVALUATION_FAILED";result:CapabilityRequirementRelationEvaluationResult}|{disposition:"NOT_EVALUATED"}>; }
