import { eq } from "drizzle-orm";
import type { PostgresJsDatabase } from "drizzle-orm/postgres-js";
import { assertEvolutionInputState, stableEvolutionInput, type EvolutionInputState, type EvolutionInputStateRepository } from "../../relation/evolution-input";
import { assertRecommendationPolicyRevision, assertRecommendationProposal, sameRecommendationData, stableRecommendation } from "../../relation/recommendation-proposal/contract";
import { deriveRecommendationProposal, type RecommendationPolicyImplementation, type RecommendationPolicyImplementationRegistry } from "../../relation/recommendation-proposal/producer";
import type { RecommendationPolicyRevisionRepository, RecommendationProposalRepository } from "../../relation/recommendation-proposal/persistence";
import type { RecommendationPolicyRevision, RecommendationProposal, RecommendationProposalItem } from "../../relation/recommendation-proposal/types";
import { recommendationPolicyRevisions, recommendationPolicyRules, recommendationProposals, recommendationProposalItems, recommendationProposalRequirementReferences, recommendationProposalAggregateReferences, recommendationProposalRelationReferences, recommendationProposalResultReferences, recommendationProposalOperandReferences } from "./postgres-schema";

const fail=(code:string):never=>{throw new Error(code)};
const sorted=(v:string[])=>[...new Set(v)].sort();
const equal=(a:string[],b:string[])=>a.length===b.length&&a.every((x,i)=>x===b[i]);
const policyRules=(v:RecommendationPolicyRevision)=>v.rules.map(rule=>stableRecommendation(rule)).sort();
const source=(v:RecommendationProposalItem)=>{const {sourceEvolutionInputItemOrdinal:_ordinal,recommendationDisposition:_disposition,recommendationKind:_kind,...item}=v;return item};
const itemKey=(v:RecommendationProposalItem)=>stableRecommendation(source(v));
const references=(v:RecommendationProposal)=>({
  items:v.items.map(item=>`${item.sourceEvolutionInputItemOrdinal}:${itemKey(item)}:${item.recommendationDisposition}:${item.recommendationKind??""}`).sort(),
  requirements:sorted(v.items.flatMap(item=>item.targetRequirementEntityId?item.targetRequirementRevisionIds.map(revision=>`${item.targetRequirementEntityId}:${revision}`):[])),
  aggregates:sorted(v.items.flatMap(item=>item.requirementRelationAggregateId?[item.requirementRelationAggregateId]:[])),
  relations:sorted(v.items.flatMap(item=>item.capabilityRequirementRelationId?[item.capabilityRequirementRelationId]:[])),
  results:sorted(v.items.flatMap(item=>item.capabilityRequirementRelationEvaluationResultId?[item.capabilityRequirementRelationEvaluationResultId]:[])),
  operands:sorted(v.items.flatMap(item=>item.candidateCapabilityOperandId?[item.candidateCapabilityOperandId]:[])),
});

/** PostgreSQL reads use the exact historical EIS and RPR as validators: FK existence alone never proves a proposal item belongs to its source. */
export class PostgresRecommendationPolicyRevisionRepository implements RecommendationPolicyRevisionRepository {
  constructor(private readonly database:PostgresJsDatabase){}
  async getRecommendationPolicyRevisionById(id:string):Promise<RecommendationPolicyRevision|null>{
    const rows=await this.database.select().from(recommendationPolicyRevisions).where(eq(recommendationPolicyRevisions.recommendationPolicyRevisionId,id)).limit(1);if(!rows.length)return null;
    try {const row=rows[0],value=row.payload;assertRecommendationPolicyRevision(value);
      if(row.recommendationPolicyRevisionId!==value.recommendationPolicyRevisionId||row.recommendationPolicyImplementationVersion!==value.recommendationPolicyImplementationVersion||row.actorId!==value.provenance.actorId||row.authorityEvidenceRef!==value.provenance.authorityEvidenceRef||row.schemaVersion!==value.schemaVersion||row.createdAt!==value.createdAt)fail("ERR_RECOMMENDATION_POLICY_REVISION_PERSISTENCE_FAILED");
      const rules=await this.database.select().from(recommendationPolicyRules).where(eq(recommendationPolicyRules.recommendationPolicyRevisionId,id));
      if(!equal(policyRules(value),rules.map(rule=>stableRecommendation({evolutionInputClass:rule.evolutionInputClass,action:rule.action,recommendationKind:rule.recommendationKind})).sort()))fail("ERR_RECOMMENDATION_POLICY_REVISION_PERSISTENCE_FAILED");
      return structuredClone(value);
    }catch{return fail("ERR_RECOMMENDATION_POLICY_REVISION_PERSISTENCE_FAILED")}
  }
  async persistRecommendationPolicyRevision(value:RecommendationPolicyRevision):Promise<RecommendationPolicyRevision>{
    assertRecommendationPolicyRevision(value);const existing=await this.getRecommendationPolicyRevisionById(value.recommendationPolicyRevisionId);if(existing){if(!sameRecommendationData(existing,value))fail("ERR_RECOMMENDATION_PROPOSAL_IMMUTABLE_CONFLICT");return existing as RecommendationPolicyRevision}
    try {await this.database.transaction(async transaction=>{await transaction.insert(recommendationPolicyRevisions).values({recommendationPolicyRevisionId:value.recommendationPolicyRevisionId,recommendationPolicyImplementationVersion:value.recommendationPolicyImplementationVersion,actorId:value.provenance.actorId,authorityEvidenceRef:value.provenance.authorityEvidenceRef,schemaVersion:value.schemaVersion,createdAt:value.createdAt,payload:structuredClone(value)}).onConflictDoNothing();for(const [index,rule] of value.rules.entries())await transaction.insert(recommendationPolicyRules).values({referenceId:`${value.recommendationPolicyRevisionId}:rule:${index}`,recommendationPolicyRevisionId:value.recommendationPolicyRevisionId,evolutionInputClass:rule.evolutionInputClass,action:rule.action,recommendationKind:rule.recommendationKind}).onConflictDoNothing()})}catch{return fail("ERR_RECOMMENDATION_POLICY_REVISION_PERSISTENCE_FAILED")}
    const reread=await this.getRecommendationPolicyRevisionById(value.recommendationPolicyRevisionId);if(!reread)fail("ERR_RECOMMENDATION_POLICY_REVISION_PERSISTENCE_FAILED");if(!sameRecommendationData(reread,value))fail("ERR_RECOMMENDATION_PROPOSAL_IMMUTABLE_CONFLICT");return reread as RecommendationPolicyRevision;
  }
}

export class PostgresRecommendationProposalRepository implements RecommendationProposalRepository {
  constructor(private readonly database:PostgresJsDatabase,private readonly evolutionInputs:EvolutionInputStateRepository,private readonly policies:RecommendationPolicyRevisionRepository,private readonly implementations:RecommendationPolicyImplementationRegistry){}
  private async assertSource(value:RecommendationProposal){
    const eis=await this.evolutionInputs.getEvolutionInputStateById(value.evolutionInputStateId);if(!eis)fail("ERR_RECOMMENDATION_PROPOSAL_PERSISTENCE_FAILED");
    const policy=await this.policies.getRecommendationPolicyRevisionById(value.recommendationPolicyRevisionId);if(!policy)fail("ERR_RECOMMENDATION_PROPOSAL_PERSISTENCE_FAILED");
    assertEvolutionInputState(eis);assertRecommendationPolicyRevision(policy);
    if(eis.tensionStateId!==value.tensionStateId||eis.roleRelationId!==value.roleRelationId||eis.verifiedCapabilitySnapshotId!==value.verifiedCapabilitySnapshotId||eis.targetRoleProfileRevisionId!==value.targetRoleProfileRevisionId||eis.targetRoleRequirementInventoryId!==value.targetRoleRequirementInventoryId||policy.recommendationPolicyImplementationVersion!==value.recommendationPolicyLineage.recommendationPolicyImplementationVersion)fail("ERR_RECOMMENDATION_PROPOSAL_PERSISTENCE_FAILED");
    const implementation=this.implementations.resolveRecommendationPolicyImplementation(policy.recommendationPolicyImplementationVersion);if(!implementation||implementation.version!==policy.recommendationPolicyImplementationVersion)fail("ERR_RECOMMENDATION_PROPOSAL_POLICY_IMPLEMENTATION_UNAVAILABLE");
    const expected=deriveRecommendationProposal(eis,policy,implementation as RecommendationPolicyImplementation,value.createdAt);if(!sameRecommendationData(expected,value))fail("ERR_RECOMMENDATION_PROPOSAL_PERSISTENCE_FAILED");
  }
  async getRecommendationProposalById(id:string):Promise<RecommendationProposal|null>{
    const rows=await this.database.select().from(recommendationProposals).where(eq(recommendationProposals.recommendationProposalId,id)).limit(1);if(!rows.length)return null;
    try {const row=rows[0],value=row.payload;assertRecommendationProposal(value);
      if(row.recommendationProposalId!==value.recommendationProposalId||row.evolutionInputStateId!==value.evolutionInputStateId||row.recommendationPolicyRevisionId!==value.recommendationPolicyRevisionId||row.tensionStateId!==value.tensionStateId||row.roleRelationId!==value.roleRelationId||row.verifiedCapabilitySnapshotId!==value.verifiedCapabilitySnapshotId||row.targetRoleProfileRevisionId!==value.targetRoleProfileRevisionId||row.targetRoleRequirementInventoryId!==value.targetRoleRequirementInventoryId||row.schemaVersion!==value.schemaVersion||row.createdAt!==value.createdAt)fail("ERR_RECOMMENDATION_PROPOSAL_PERSISTENCE_FAILED");
      const [items,requirements,aggregates,relations,results,operands]=await Promise.all([this.database.select().from(recommendationProposalItems).where(eq(recommendationProposalItems.recommendationProposalId,id)),this.database.select().from(recommendationProposalRequirementReferences).where(eq(recommendationProposalRequirementReferences.recommendationProposalId,id)),this.database.select().from(recommendationProposalAggregateReferences).where(eq(recommendationProposalAggregateReferences.recommendationProposalId,id)),this.database.select().from(recommendationProposalRelationReferences).where(eq(recommendationProposalRelationReferences.recommendationProposalId,id)),this.database.select().from(recommendationProposalResultReferences).where(eq(recommendationProposalResultReferences.recommendationProposalId,id)),this.database.select().from(recommendationProposalOperandReferences).where(eq(recommendationProposalOperandReferences.recommendationProposalId,id))]);
      const expected=references(value);if(!equal(expected.items,items.map(item=>`${item.sourceOrdinal}:${item.sourceKey}:${item.recommendationDisposition}:${item.recommendationKind??""}`).sort())||!equal(expected.requirements,requirements.map(item=>`${item.targetRequirementEntityId}:${item.targetRequirementRevisionId}`).sort())||!equal(expected.aggregates,aggregates.map(item=>item.requirementRelationAggregateId).sort())||!equal(expected.relations,relations.map(item=>item.capabilityRequirementRelationId).sort())||!equal(expected.results,results.map(item=>item.capabilityRequirementRelationEvaluationResultId).sort())||!equal(expected.operands,operands.map(item=>item.candidateCapabilityOperandId).sort()) )fail("ERR_RECOMMENDATION_PROPOSAL_PERSISTENCE_FAILED");
      await this.assertSource(value);return structuredClone(value);
    }catch(error){if(error instanceof Error&&error.message==="ERR_RECOMMENDATION_PROPOSAL_POLICY_IMPLEMENTATION_UNAVAILABLE")throw error;return fail("ERR_RECOMMENDATION_PROPOSAL_PERSISTENCE_FAILED")}
  }
  async persistRecommendationProposal(value:RecommendationProposal):Promise<RecommendationProposal>{
    assertRecommendationProposal(value);const existing=await this.getRecommendationProposalById(value.recommendationProposalId);if(existing){if(!sameRecommendationData(existing,value))fail("ERR_RECOMMENDATION_PROPOSAL_IMMUTABLE_CONFLICT");return existing as RecommendationProposal}await this.assertSource(value);
    const expected=references(value);try {await this.database.transaction(async transaction=>{await transaction.insert(recommendationProposals).values({recommendationProposalId:value.recommendationProposalId,evolutionInputStateId:value.evolutionInputStateId,recommendationPolicyRevisionId:value.recommendationPolicyRevisionId,tensionStateId:value.tensionStateId,roleRelationId:value.roleRelationId,verifiedCapabilitySnapshotId:value.verifiedCapabilitySnapshotId,targetRoleProfileRevisionId:value.targetRoleProfileRevisionId,targetRoleRequirementInventoryId:value.targetRoleRequirementInventoryId,schemaVersion:value.schemaVersion,createdAt:value.createdAt,payload:structuredClone(value)}).onConflictDoNothing();for(const [index,item] of value.items.entries())await transaction.insert(recommendationProposalItems).values({referenceId:`${value.recommendationProposalId}:item:${index}`,recommendationProposalId:value.recommendationProposalId,sourceOrdinal:item.sourceEvolutionInputItemOrdinal,sourceKey:itemKey(item),recommendationDisposition:item.recommendationDisposition,recommendationKind:item.recommendationKind}).onConflictDoNothing();for(const reference of expected.requirements){const [entity,revision]=reference.split(":");await transaction.insert(recommendationProposalRequirementReferences).values({referenceId:`${value.recommendationProposalId}:req:${reference}`,recommendationProposalId:value.recommendationProposalId,targetRequirementEntityId:entity,targetRequirementRevisionId:revision}).onConflictDoNothing()}for(const reference of expected.aggregates)await transaction.insert(recommendationProposalAggregateReferences).values({referenceId:`${value.recommendationProposalId}:aggregate:${reference}`,recommendationProposalId:value.recommendationProposalId,requirementRelationAggregateId:reference}).onConflictDoNothing();for(const reference of expected.relations)await transaction.insert(recommendationProposalRelationReferences).values({referenceId:`${value.recommendationProposalId}:relation:${reference}`,recommendationProposalId:value.recommendationProposalId,capabilityRequirementRelationId:reference}).onConflictDoNothing();for(const reference of expected.results)await transaction.insert(recommendationProposalResultReferences).values({referenceId:`${value.recommendationProposalId}:result:${reference}`,recommendationProposalId:value.recommendationProposalId,capabilityRequirementRelationEvaluationResultId:reference}).onConflictDoNothing();for(const reference of expected.operands)await transaction.insert(recommendationProposalOperandReferences).values({referenceId:`${value.recommendationProposalId}:operand:${reference}`,recommendationProposalId:value.recommendationProposalId,candidateCapabilityOperandId:reference}).onConflictDoNothing()})}catch(error){if(error instanceof Error&&error.message==="ERR_RECOMMENDATION_PROPOSAL_POLICY_IMPLEMENTATION_UNAVAILABLE")throw error;return fail("ERR_RECOMMENDATION_PROPOSAL_PERSISTENCE_FAILED")}
    const reread=await this.getRecommendationProposalById(value.recommendationProposalId);if(!reread)fail("ERR_RECOMMENDATION_PROPOSAL_PERSISTENCE_FAILED");if(!sameRecommendationData(reread,value))fail("ERR_RECOMMENDATION_PROPOSAL_IMMUTABLE_CONFLICT");return reread as RecommendationProposal;
  }
}
