import type { EvolutionInputClass, EvolutionInputDerivationDisposition, EvolutionInputItem } from "../evolution-input";
export type RecommendationPolicyRuleAction="PROPOSE"|"ABSTAIN";
export type RecommendationKind="DEMONSTRATED_LEVEL_RECOMMENDATION"|"EVIDENCE_STRENGTHENING_RECOMMENDATION"|"SEMANTIC_UNCERTAINTY_RESOLUTION_RECOMMENDATION"|"TARGET_UNCERTAINTY_RESOLUTION_RECOMMENDATION";
export type RecommendationDisposition="PROPOSED"|"ABSTAINED"|"NOT_RECOMMENDABLE"|"BLOCKED_BY_UNCERTAINTY"|"BLOCKED_BY_UPSTREAM_FAILURE"|"NOT_APPLICABLE";
export interface RecommendationPolicyRevision { recommendationPolicyRevisionId:string; provenance:{origin:"EXPLICIT_POLICY_DECLARATION";actorId:string;authorityEvidenceRef:string}; rules:Array<{evolutionInputClass:Extract<EvolutionInputClass,"INCREASE_DEMONSTRATED_LEVEL_INPUT"|"STRENGTHEN_EVIDENCE_INPUT"|"RESOLVE_SEMANTIC_UNCERTAINTY_INPUT"|"RESOLVE_TARGET_UNCERTAINTY_INPUT">;action:RecommendationPolicyRuleAction;recommendationKind:RecommendationKind|null}>; recommendationPolicyImplementationVersion:string; schemaVersion:"RECOMMENDATION_POLICY_REVISION_V1"; createdAt:string; }
/** One exact EIS item is preserved as one policy-bounded proposal record; it is never a decision, commitment, or action. */
export interface RecommendationProposalItem extends EvolutionInputItem { sourceEvolutionInputItemOrdinal:number; recommendationDisposition:RecommendationDisposition; recommendationKind:RecommendationKind|null; }
/** Immutable policy-bounded proposal for exact EIS × RPR, never a current recommendation pointer. */
export interface RecommendationProposal { recommendationProposalId:string;evolutionInputStateId:string;tensionStateId:string;roleRelationId:string;verifiedCapabilitySnapshotId:string;targetRoleProfileRevisionId:string;targetRoleRequirementInventoryId:string;recommendationPolicyRevisionId:string;items:RecommendationProposalItem[];recommendationPolicyLineage:{recommendationPolicyImplementationVersion:string};proposalState:"PROPOSAL_ONLY";authorityState:"RECOMMENDATION_POLICY_BOUND";schemaVersion:"RECOMMENDATION_PROPOSAL_V1";createdAt:string; }
